### ISSUE TITLE
Suggestion: Randomize Holy Blood Bonus in Chunks

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#104]
I tried the option that randomizes growth bonuses granted by Holy Blood and they're randomized in chunks of 5 in all stats. I think it would be neat to have an option that allows to choose how big the chunks (30% or 10% etc...) should be, maybe even with a separate option for HP so that as in vanilla all holy blood boost HP growth by a certain amount.
  I would also add two toggleable options: one to prevent magic and strength focused Holy Bloods from giving out boosts in Str/Mag respectively and one to evenly spread the bonuses (so that you don't end up with 8 holy bloods giving only a strength boost etc...) though the latter might be complicated? I dunno really.

**Comment by lushen124** [comment]
* I can understand 10%, but 30% seems a bit specific. I suspect you're using 30% because that's what the vanilla blood uses, but since I allow any amount of growth bonuses, 30% isn't going to be very useful when randomizing, not to mention 30% isn't a great divisor for many growth totals. The reason I use 5% is because it is a divisor for all possible values you can use for that input box (I limited it to multiples of 5). 10% is somewhat more defensible since it's a divisor to half of the values possible (with a random leftover 5% that has to be allocated).
* HP specific boosts are a bit odd as well, since not all bloods have a +20% HP boost (only most of them). Is the goal to mirror vanilla or to apply a universal HP boost baseline to all bloods that can be specified? It'd basically end up being a different spinner that caps at the value of the total boost.
* An option to make sure magic bloods get magic and strength bloods get strength wouldn't be too difficult. Would you want the chance of getting the opposite trait or completely remove that possibility?
* As for making sure bloods are evenly spread, filtering out exact matches wouldn't be too difficult, but similar boosts might be a bit difficult. For example, if two bloods both gave +20% HP and +30% STR, that could safely considered identical, or even +20% HP and +30% MAG (though I'm not sure if that case should be considered identical). However, +20% HP and +25% STR and +5% LCK would not be considered the same and would be allowed to stand.

**Comment by lushen124** [comment]
Perhaps you may just want a shuffle option? Where it takes the non-HP growths for each bloods and randomly shuffles them around so that you end up with the usual 10-10-10 or 30 distribution.

**Comment by koumal8** [comment]
1) And... what if the chunk value the user inputs is not a divisor of the total growth bonus selected? Couldn't the program just randomly assign the leftover amount in a single chunk? You put 50% tot bonus and 50% chunk, you get one chunk; you put 50% tot bonus and 35% chunk, you get one 35% chunk + one 15% chunk; limiting user input to multiples of 5% seems good to me.
  2) Yeah, I understand handling HP would probably require a different spinner completely, you don't want to end up with holy bloods giving a growth bonus to HP only; applying a specific HP boost baseline to every blood would probably be enough.
  3) I'd want this toggleable option to completely remove the possibility of Str bloods getting a Mag bonus and viceversa; in case this option isn't toggled, it would be neat if there was another toggleable option to "Adjust Str/Mag bonus by blood" as you already implemented for classes
  4) Two bloods giving growth boosts to the same stats (excluding HP) should be considered identical, regardless of the amounts by which the growths were boosted, to keep it sane I think? A bonus to Str and a bonus to Mag should not be considered identical for the purpose of this feature because... I don't see a reason? We don't want a blood giving a boost to Mag+Spd (for example) to prevent other bloods from giving a boost to Str+Spd, do we? I see a possible problem arising from this (leaving aside HP for a moment since it should probably be its own thing):
        blood A gets randomized into Str+Spd bonus;
        blood B gets randomized into Str+Def bonus;
        blood C gets randomized into Str+Spd+Def bonus;
- is blood B identical to blood A? should blood B be filtered out? I'd say NO
- is blood C identical to blood A? should blood C be filtered out? I'd say YES
- is blood C identical to blood B? should blood C be filtered out? I'd say YES
  Now to explain myself. Thinking about bloods as sets of bonuses in specific stats, I would define blood A as being identical to blood B if and only if the intersection of blood A and blood B contains **at least two boosted stats**; this way:
  Str+Spd+Def and Str+Skl+Lck are NOT identical
  Str+Spd+Def and Str+Spd+Lck ARE identical
  Str+Spd+Def+Lck and Str+Spd+Skl+Res ARE identical
  Str+Spd+Def+Lck and Str+Skl+Res+Mag are NOT identical.
If this is too complicated to code (and it sounds like it) it would still be fine to define identical bloods as bloods giving bonuses to the exact same stats, so that Str+Spd=/=Str+Def=/=Str+Spd+Def (none of this combinations filters out the other two) which is fine and dandy enough for me.
  5) A shuffle option could be fun yeah, I just think the system I described would be more fun, if only because

**Comment by lushen124** [comment]
1. The spinner should already be automatically setting the value to the nearest 5%, but if it's not, then fair point. And yeah, the logic would eventually end up assigning the remainder.
3. That's probably what I'd call the checkbox, but its mechanics might be different. Instead of treating STR and MAG as separate stats, they're just treated as one when it assigns chunks. The result goes to one or the other, depending on the blood. That's pretty easy to do.
4. This is a good start. And it's not too bad to toss out two bloods that share at least 2 areas, but it needs to work with any sized chunk distribution and any total growth value. I could probably use that basic idea and come up with something though. I may not make it so that it drops any two boosted stats, but maybe if the two **highest boosted** stats (disregarding HP and the secondary attacking stat) are the same.

Example:

-|HP|STR|MAG|SKL|SPD|DEF|RES|LCK
-|-|-|-|-|-|-|-|-
Baseline|20%|**10%**||5%|5%|**10%**|||
|||||||
Duplicate 1|20%|**20%**||||**10%**|||
Duplicate 2|20%|**15%**||||**10%**|5%||
Duplicate 3|10%|**15%**|||10%|**15%**||
Duplicate 4|10%|**10%**||5%|5%|**10%**|5%|5%
|||||||
Unique 1|20%|5%||**10%**|**10%**|5%|||
Unique 2|20%|**10%**||5%|5%||**10%**||
Unique 3|10%||**30%**|||**10%**|
Unique 4|10%||**10%**|5%|5%|5%|**10%**|5%

**Comment by koumal8** [comment]
2) Would the chance of physical bloods getting mag and viceversa still be there though, in a differently coded randomization option?
3) I though it would be way too convoluted, but if you can make that logic work that would be awesome!

**Comment by lushen124** [comment]
I feel like it should just be physical bloods getting strength and magical bloods getting magic. It makes no sense for a physical blood to get magic growth. I'll just make that the default behavior. I don't think an option to match STR/MAG appropriately is necessary.

**Comment by lushen124** [comment]
So, the funny thing is, I forgot that I had already added logic to make sure blood bonuses for STR/MAG already respected your weapon type by default, so now the option is to remove that, if you so desired. :)
