### ISSUE TITLE
List of the little general updates/nice features?

### ISSUE THREAD

**Issue by Zswords** [lushen124/Universal-FE-Randomizer#111]
Kind of a simple one, but I found myself in FE7 with a Brigand saying 'I don't know what I need to promote you' and couldn't ctrl+f my way to victory in the read me. I did some bruteforce save loading to verify Knights Crest for Knight Lord and Hero's for Blade Lord, and Knight worked for Soldier, buuut Hero isn't working for Brigand. That leaves me pretty much with just Ocean left.

Also: On that list, have you considered adding flier effectiveness to the Emblem Bow?

**Comment by lushen124** [comment]
It actually is Ocean Seal for brigand. 🙂 Maybe it wasn't too obvious, but I was basing it off of berserkers, which normally come from pirates, and therefore, Ocean Seal.

For promotion items (and maybe I'll add something in the changelog to note these things):

* Soldiers use Knights Crests.
* Most lord classes use Knight Crests. The only exception is Lyn, who uses a Hero Crest.
* Brigands use Ocean Seals. I may add Hero Crest to this list since that's what the wiki says they use in FE6.
* FE8 monsters are mapped to their "closest" human equivalent. Revenants, non-bow Bonewalkers, and Mauthe Doogs map to Hero Crests, Tarvos and Baels map to Knight Crests, Mogalls map to Guiding Rings, Gargoyles map to Elysian Whips, and Bow Bonewalkers map to Orion's Bolt.

And I wasn't planning on modifying any weapons directly. Emblem Bow specifically has no effectiveness data on it, and without knowing for sure whether that was intentional or not, I didn't add it. I could add it though. It's not hard to do so.
