### ISSUE TITLE
FE4: AI using holy weapons they don't have holy blood for

### ISSUE THREAD

**Issue by LJCLilio** [lushen124/Universal-FE-Randomizer#113]
In chapter 6, Schmidt holds the item Lex picks up in chapter 1, as expected. In my case, Lex's item was Helswath, and Schmidt was holding it and dropped it as normal. However, he was a great knight, and in spite of lacking the holy blood to use it, he would equip it if I attacked him from range.

**Comment by lushen124** [comment]
Just FYI, FE4's mechanics actually don't check to see if the character can use the weapon when counterattacking, so enemies will always counter with from range if they have a weapon that is capable of doing so, regardless of whether they can use the weapon. This is why there's logic to make sure nobody gets stuck with a weapon they shouldn't have, and they aren't allowed to drop a weapon they can't use. In most cases, this actually softlocks the game, but in your case, it works because an animation actually exists for that combination.

Therefore, the solution is actually to make sure Lex's weapon there can't be a holy weapon (Schmidt's class, if bosses are allowed to change class, will change to match the weapon type Lex uses.) I also need to verify that the Brave Axe is accounted for in my list of shared weapons.

**Comment by LJCLilio** [comment]
Would it matter that it was Helswath specifically? Every other holy weapon has the same regular range as a normal weapon equivalent (1 range swords/lances, 2 range bow, 1-2 range tomes) so it seems that this would only happen for Helswath, unless I'm mistaken.

**Comment by lushen124** [comment]
No, it's just any weapon. FE4 makes no checks as to whether an enemy can use a weapon before counterattacking. The same issues happen when a non-mage gets assigned (or is supposed to drop) a magic tome.
