### ISSUE TITLE
FE7: CH27 force promote Eliwood demotes them instead

### ISSUE THREAD

**Issue by Alventenie** [lushen124/Universal-FE-Randomizer#124]
In Chapter 27 Cog of Destiny for Eliwood when Athos gives you a heaven seal to force promote you, if you are a promoted class already it will just demote you to your base class. 

I had a Sage Eliwood that got demoted to a mage (and losing any stats above mages caps). Is this intended since we can promote our lords without heaven seals if they are different classes.

**Comment by lushen124** [comment]
It's not intentional, no. I wish I knew enough ASM to just skip the promotion step if he's already promoted but in the meantime, the easiest fix is that I can make promoted classes promote into themselves, though the effect of that is that these characters gain promotion bonuses a second time when that happens, which I don't think should be a huge issue if it's just the lord.
