### ISSUE TITLE
Mac OS Version: stuck randomizing Holy Blood Bonuses

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#132]
Same old Mac OS High Sierra, Yune has been stuck randomizing holy blood growth bonuses for a good 10 minutes, is this normal?  How much did it take you in during testing? I may retry later and give it more time. These were the options:
https://www.dropbox.com/s/k2kcmv4j9d2afhh/Schermata%202019-04-22%20alle%2014.31.20.png?dl=0

**Comment by koumal8** [comment]
UPDATE: I tried a couple more times and the problem arises when toggling the box to generate unique bonuses with 50% Growth total, 30% chunks and 20% baseline HP. Thing is: said combination of options allows for only 9 unique bloods (50% bonus to HP and 20%HP+30% bonus for each other stat), but there are 13 holy bloods in the game; do you have a logic in place to disregard uniqueness of holy bloods when there are no other possible unique holy bloods? Or does it get stuck in a loop?

**Comment by lushen124** [comment]
I didn't consider that combination, but it probably gets stuck in a loop, since it can't fulfill both conditions. There's only 6 real stats that can be distributed and if there's only 1 pass (with a 30% chunk), then there's only 6 combinations/permutations across 12 bloods. At a minimum, you'd need 2 passes, which will give you 15 combinations if the two passes are equal or 30 permutations if the two passes aren't equal. I'd suspect that if you have a total of 55% with 20% base HP and 30% chunks, that would randomize fine, because then you'd get 30% for the first pass and 5% with the second.

I'll add something in there to calculate the number of passes at UI time so that it'll gray out the unique bloods if it can't fulfill it.
