### ISSUE TITLE
FE4: Randomizing Holy Bloods conflicts with consistent Growths Rates

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#133]
OK so, this is with randomizing holy bloods, holy blood growth bonuses but not growths themselves. Ulir was randomized into giving +30% Res growth, Sigurd was randomized into a Warrior with Major Ulir... and he now has 0% Lck. I think that's because Yune tries to preserve his Lck growth regardless of holy blood, sets it to 0% and then adds the Ulir bonus... which has now changed to +30% Res and is no longer +30% Lck! And so Sigurd is left with 0% Lck. A similar thing happened with Claud where he was randomized into a Warrior with Major Neir and now has 0% Def, 50% Res (as in vanilla MajorBragi!Claud) and 30+60% Spd (which exceeds the 85% limit you wanted Yune to respect in order to avoid overflowing stats in 2nd generation, I think?).
  Proposed solution: scrap this whole "trying to preserve original growth rates" thing. I do not understand why Yune couldn't simply, when determining the new growth rates, take the personal growth rates (with holy blood bonuses excluded) and just add onto them the new holy blood bonuses without doing this whole lowering/increasing personal growth rates when a holy blood is added/changed etc... If one tries to randomize growth rates via adding a delta factor it gets even more complicated. Or at least make it an option and, when toggled, have it work correctly by fixing the above mentioned issue. It seems like a lot of work to me though.
  And then if a growth rate exceeds 85% just set it to 85%.

**Comment by lushen124** [comment]
I believe the 85% is limited to personal growths, not final growths. So they can have over 85% total growth, but not over 85% personal growth in any area.

>  I do not understand why Yune couldn't simply, when determining the new growth rates, take the personal growth rates (with holy blood bonuses excluded) and just add onto them the new holy blood bonuses without doing this whole lowering/increasing personal growth rates when a holy blood is added/changed etc...

Mostly because Yune isn't the one doing the adding. I only have two levers to pull: the character's personal growth rates, and the holy blood's growth bonuses. The game logic (which I can't change without re-coding the game itself) is the one adding them together to get the final growth rate for a character (it actually works the same way as base stats, where the game is going to take your personal base and add it to the class base). I can't directly set a character's final growth rates (just as you can't directly set a character's base stats directly). 

Obviously we're pulling the second lever willingly, so the only question is whether to adjust the first. Since you can't have a negative personal growth, it can't guarantee that your final growth rate hasn't changed if you use this option. But it does try its best to keep them as close to normal as possible. When it's not possible, it errs on the side of giving you more growth, rather than less (well, it can't give you less because, as I said, you can't have negative growth).

To your point, I can make that second lever an option if you think that's more of what you want. Just to give you an idea of what that would do. Let's say Option 1 is to adjust growths (what Yune does today) and Option 2 is to not adjust growths.

Sigurd|HP|STR|MAG|SKL|SPD|DEF|RES|LCK
-|-|-|-|-|-|-|-|-
Personal Growths|70%|30%|5%|30%|30%|40%|5%|20%
Major Baldr (Normal)|40%|20%|-|20%|-|-|-|20%
**Final Growths (Normal)**|**110%**|**50%**|**5%**|**50%**|**30%**|**40%**|**5%**|**40%**
||||||||||
Major Baldr (Example Randomization)|20%|-|10%|-|-|30%|20%|20%
|||||||||||
Adjusted Personal Growths (Option 1)|90%|50%|0%|50%|30%|10%|0%|20%
**Final Growths (Option 1)**|**110%**|**50%**|**10%**|**50%**|**30%**|**40%**|**20%**|**40%**
|||||||||||
**Final Growths (Option 2)**|**90%**|**30%**|**15%**|**30%**|**30%**|**70%**|**25%**|**40%**

**Comment by koumal8** [comment]
1) I'd love to have Option 2 as an option, yes
2) There's still something wrong with those 0% I got though, isn't it? Isn't Yune pulling the levers in the wrong order?

**Comment by lushen124** [comment]
0% personal growth isn't that odd. It'd happen if you got a blood bonus that was larger than what your normal growth for it was. In fact, it happened in my example. Sigurd's RES growth is only 5%, but his blood got randomized to give +20%. This is expected behavior. Not ideal behavior, but expected behavior.

**Normal Sigurd** 5% personal RES + 0% blood RES = 5% total RES
**With Random Baldr** 0% personal RES + 20% blood RES = 20% total RES

Option 1 aims to keep the third number the same by adjusting the first (not always successfully, because the first number can't be negative).

In a more normal example, look at HP in the example above. 

**Normal Sigurd** 70% personal HP + 40% blood HP = 110% total HP
**With Random Baldr** 90% personal HP + 20% blood HP = 110% total HP

**Comment by koumal8** [comment]
No no, I meant: Sigurd and Claud have 0% **total **growth****, they got a holy blood without bonuses to those stats. Look at the changelog.
https://www.dropbox.com/s/1ccsos0lq6m9bw2/FE4Random.html?dl=0

**Comment by lushen124** [comment]
Ooooh, yeah, that is a problem. Nobody should be losing growth without randomizing growths. Let me look into it.

**Comment by koumal8** [comment]
"I think that's because Yune tries to preserve his Lck growth regardless of holy blood, sets it to 0% and then tries to add the Major Ulir bonus (+30%Lck x 2)... which has however changed to +30% Res and is no longer +30% Lck! And so Sigurd is left with 0% Lck." Again, maybe this is why?

**Comment by lushen124** [comment]
Yeah, that sounds about right.

And my mistake, I actually confused one operation for the other. When you assign holy blood to characters, that does adjust their growths, but if you just randomize holy blood bonuses, that **does not** adjust personal growths.

**Comment by koumal8** [comment]
Adding onto this without opening a new issue, I hope you read this: without randomizing holy blood bonuses, I think Yune may be messing something up when physical characters get randomized into magical ones with major magic blood? If I understood correctly, Fala!Sigurd should have 0% personal mag + 60% mag bonus from Major Fala under the current logic... except this one has 45%+60% mag growth.
https://www.dropbox.com/s/1ccsos0lq6m9bw2/FE4Random.html?dl=0

**Comment by lushen124** [comment]
Hmm... that's a new one. Let me just look over all of the holy blood logic again. There probably is something I messed up with STR/MAG swaps. Thanks for the report!
