### ISSUE TITLE
Settings result in negative base stats that wrap around

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#136]
I'm using the new 0.8.4 version and using the "Retain Personal Bases" option on FE7. The Chapter 2 boss Glass has negative stats in the log, but they show up in game as very high stats. Here are screenshots of Glass and my settings when I randomized this one, in case it's not just the "Retain Personal Bases" option.
![peerless_swordplay](https://user-images.githubusercontent.com/18605346/56541196-a43ff000-6530-11e9-82c0-bcf4fb5ffe0c.PNG)
![yune_settings](https://user-images.githubusercontent.com/18605346/56541198-a6a24a00-6530-11e9-9c6b-731aea434b2d.PNG)

**Comment by lushen124** [comment]
Weird. I know Glass has negative offsets, so I'll take a look. Thanks for reporting!

**Comment by lushen124** [comment]
Oh, I see what it is. It's the reason why I didn't retain personal bases to begin with.

Glass has a -4 in Skill and -3 in Speed. This is to make him not too hard in Ch. 2 as a Mercenary, since at 0, he would have 8 SKL and 8 SPD, which is faster than Sain and Kent (and probably shatters the weapon triangle concept). But since he changed into a Knight, with a base 2 SKL and 0 SPD, those values underflowed and wrapped around.

I'll cap it to 0 on the lower side. The other two options should handle this appropriately since they adjust things based on final stats.
