### ISSUE TITLE
Suggestion for FE7: Lyn mode consistency

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#161]
There are two versions of at least some of the units recruited in Lyn mode of FE7, including Lyn. It appears that both versions of these characters are randomized separately, at least for base stats. The log only shows the versions that are recruited in Eliwood/Hector mode.

I didn't notice this before because I've mostly played with randomized recruitment. When I used the new 0.8.5 ability to not randomize lord recruitment, though, I discovered that my level 1 Lyn mode Lyn had stats that differ from the log Lyn in both directions (higher strength, lower HP, etc.). Are the growths in the log also different from the ones that my Lyn has? I'd have to go into Nightmare to check, defeating the purpose of the log. I assume that people who aren't randomizing recruitment are getting bad info from the log for other Lyn mode units too. (I had thieves not be included plenty of times, and never saw this problem with Matthew, so it's not every unit.)

I could keep listing things that are unclear, but instead I'll just give my suggestion: Make it consistent. Randomize only one version of these characters, then autolevel using the randomized growths to get the bases for the other version. Display whichever one you prefer in the log, but indicate which one it is somehow.

EDIT: I think when recruitment is randomized, units who fill into Lyn mode unit slots are getting their stats determined based on the versions of the slot units that would exist in Eliwood/Hector mode. So for instance, with the Relative Base Stats setting, a character replacing Lyn will use her 11 speed from the level 4 version of her in Eliwood/Hector mode as the highest stat number, but then they still start at level 1 with those level 4 stats.

EDIT^2: The above seems to only apply with the Relative Base Stats setting. With either of the autolevel settings for bases of randomized recruitment, the Lyn mode units have appropriately lower stats than the ones listed in the log. I think bases are still randomized twice, though.

**Comment by lushen124** [comment]
I think I see the problem. Throughout the randomizer, I have logic to base everything off of the canonical version of that character, which, for Sain, Kent, Lyn, Wil, Florina, and Rath, are their normal Eliwood/Hector mode versions. There are separate versions for those characters strictly for Lyn mode (in order to prevent supports from growing in Lyn mode), but the randomizer doesn't use them for determining anything. We actually don't want to consider them in random recruitment, because then those characters show up twice, but we do need to take into account having lower stats in one form vs the other form if we randomize recruitment into those slots.
