### ISSUE TITLE
FE8: Some color palettes are incorrect

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#165]
I hope this isn't a consequence of you fixing the color palettes for FE7, but now I've found some problems in FE8.
First, here's Colm in his default Thief class. As you can see, his colors are wrong.
![offcolor_colm](https://user-images.githubusercontent.com/18605346/57587057-837e1100-74c4-11e9-9b8b-98658f4c11d0.PNG)
Second, here's Paladin Garcia. This one might be the best you can do, and if so, that's fine. But it doesn't look good.
![offcolor_paladin_garcia](https://user-images.githubusercontent.com/18605346/57587068-c04a0800-74c4-11e9-8a7e-e974773a75ba.PNG)

**Comment by lushen124** [comment]
I'm pretty sure I only messed with FE7 palettes earlier, but I can revisit FE8 as well. Colm is weird because he really shouldn't need to have his palette changed.

I did change some logic in determining how to coerce different number of colors to different classes though, so that may have broken some things. Is this strictly using randomized recruitment?

**Comment by Lewa263** [comment]
I found this with randomized recruitment where the option to include thieves was NOT checked off, so Colm was always going to be a thief. Classes were not randomized. Garcia there replaced Seth, using the Use Slot Class option. I have since discovered that Colm still has these wrong colors with randomized classes and non-randomized recruitment, again with thieves not included in the randomization.
