### ISSUE TITLE
FE8: "Improve Enemy Weapons" setting doesn't work

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#166]
Even when set to a 100% chance of improved weapons, regular enemies keep their default inventories from the base game. If their classes are randomized, they may get new weapons to fit their new class, but still nothing of higher rank. The Improve Boss Weapons setting works correctly in both FE8 and FE7, and the Improve Enemy Weapons setting works correctly with FE7.

**Comment by lushen124** [comment]
Weird that it only doesn't work on FE8, considering it's the same logic used in both cases. I'll take a look.

**Comment by Vennobennu** [comment]
I had the same issue and took a look at the code. My best guess is that, because minion units in FE8 always return 0 for their leader ID when the randomizer loads them, the conditional in EnemyBuffer "if (charactersData.isBossCharacterID(leaderID))" always returns false, since 0 is not a boss character ID. 

An alternative condition might be to check for enemy+autolevel on that unit, since that is a sure sign of a generic enemy.

**Comment by lushen124** [comment]
This is a really late reply, but thanks for the assist! Just started looking over bugs and am going through the ones that are issues. I can change the condition to use starting level and alliance (and in retrospect, that's probably a better sign to begin with).

If I'm reading the Nightmare module correctly, it looks like the upper 5 bits are the level? That leaves the least significant three bits. And if I'm reading this properly, the least significant bit is the autolevel flag. NPCs have the second bit set, and enemies have the third bit set (player characters have neither bit set). Which means a 0x5 mask should find all of the minions.
