### ISSUE TITLE
Enemies using items they can drop, despite not being able to. (FE4)

### ISSUE THREAD

**Issue by bobosmith01** [lushen124/Universal-FE-Randomizer#174]
This happened on two ocassions. One, I was facing Hannibal's High Priest, who had Thoron in his inventory (I was wondering why he couldn't use it, until I remembered he normally drops something in the vanilla game, but I had "inherited" Thoron with a unit).
Tralala, I go to attack the High Priest, and....he kills me with Thoron in retaliation.

The same thing happened with Hilda's first fight, except she was a general. When attacked from range, despite her having the Silver Blade on, she attacked with Volcanon....which froze the game because Generals have no magic-casting sprite, I assume.

When I attacked her up close (before she even changed weapons, mind, though FE4 does switch boss weapons if they have a good option), she used the Silver Blade she had like normal. So I assume it has to do something with retaliation.

I have a changelog, though I don't know how to upload it? Github says it doesn't support the file type.

**Comment by lushen124** [comment]
This is actually a quirk with the FE4 mechanics. FE4 doesn't actually check to see if a character can use a weapon when counterattacking. It just equips any weapon it has at that counter range. This is problematic because weapons that aren't inherited sometime end up in enemy hands instead of the shop, which means they should drop them, but that doesn't stop them from equipping them with counterattacks. Generally we try to note these and make limitations on randomizations so that this doesn't happen. In this case, it depends on the settings.

* If minions are allowed to randomize, then the minion will be limited to a class that can use the weapon that he drops.
* If minions are not allowed to randomize, then the character passing down said weapon will be limited in their class pool to make sure that weapon can be used by the High Priest (which means this character will remain being a magic user).

Do you know who didn't pass down the Thoron from Gen 1? Also, do you know how Hilda got the Volcanon tome? I need to add these to the exception list. 🙂

**Comment by bobosmith01** [comment]
Claude passed down Thoron (he had major Tordo blood) to Arthur (who was a Bard). 
I don't believe you get Volcanon in Gen 1.

Also, another one that I think just worked out was the final boss of Chapter 8 was that he remained a General, and was able to use the Killer Bow he still had on him. Not sure if you programmed that exception in .
Not sure why KB wasn't randomized. Or maybe it was, and it was just lucky. (He didn't drop it.)

**Comment by lushen124** [comment]
Right, Thoron came from Claud's regular staff, which passes down to that high priest if it's not inherited. I'll need to make sure that high priest is locked or Claud's class (or if minion randomization is not enabled, Claud will be restricted in his class selection). I feel like this priest is already on the list, but I'll double check.

With regards to weapon replacements, the logic currently checks to see if the character can use the existing weapon first and doesn't bother changing it if the character can use the same weapon in his/her new class. So anybody randomizing into General will retain any Swords, Lances, Axes, and Bows, as Generals can use any of those weapons. In other words, weapons are only changed if they need to be changed, and they only need to be changed if their class can't use them.

**Comment by bobosmith01** [comment]
Understood. I can't think of anything that would interfere in the final chapter (I'm on that now, but I'll get back to this, and, if nothing happens, I'll close it (I think I should?). Thanks!)

**Comment by bobosmith01** [comment]
All finished! Thanks so much for your help. I hope you can fix this issue soon!

**Comment by bobosmith01** [comment]
Okay, so, I'm back, and the same thing happened with Bramsel. He was a Knight Lord, and dropped a Steel Bow. Naturally, his counterattack froze the game.

**Comment by lushen124** [comment]
Ok, I'll take a look at these cases. So far, we have three cases right?

* Priest next to Hannibal (Thoron as High Priest) - Inherited
* Hilda (Bolganone as General) - I think this is her normal weapon. If you have a changelog you can check this in the Item Log, which details where each inventory item is assigned.
* Bramsel (Steel Bow as Knight Lord) - Normally has a Knight Killer (which I think is inherited?)

**Comment by bobosmith01** [comment]
That's correct. I've played through Chapter 8, no additional errors so far.
Yes, I do believe Bramsel inherits the Knight Killer. He had a Horseslayer he dropped last playthrough.
