### ISSUE TITLE
Weapon durability reseting

### ISSUE THREAD

**Issue by mitchell-contactus** [lushen124/Universal-FE-Randomizer#176]
I set weapons to have a 'randomized' durability between 99-99. A couple missions into the game and the durability has been reset on the weapons to be the original values.
[changelog.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/3277905/changelog.zip)

**Comment by lushen124** [comment]
Based on your changelog, it looks like only siege tomes are not 99, which is probably because I have logic that treats siege tomes differently in terms of durability. Not sure if you think they should be treated the same or you want to be able to control siege tome durability separately from more regular weapons.

**Comment by Lucky0426** [comment]
I don't think this is a program issue. The way GBA FE is, most weapons reset durability when the game closes if the durability is somewhere over 60. I am unsure why this happens.

**Comment by lushen124** [comment]
If I were to guess, it's probably because the save data only allocates so many bits to track weapon durability. If the limit is 60, then I'd guess 6 bits (for a maximum value of 63). Similarly, I know the save data only allocates 5 bits to track most stats, so any attempt to go beyond 31 will drop it back down. I also know that the game generally truncates most bits (it usually does a left shift, followed by a right shift to truncate the bits).

So if your weapon has a durability of 99, that's 0x63 in hex. If we track only the front 6 bits, then we get 0x23, which is 35. Based on my testing, this is indeed what my 99 durability weapon dropped to when I reloaded the save.

As for the fix, there's not much we can do outside of capping Yune to a max value of 64 durability. It would be unreasonable to change the structure of the save data.
