### ISSUE TITLE
FE6 Reclassed Character Stats way too low

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#181]
38 HP/16 Str/8 Skl /5 Spd /6 Def /8 Lck /Def 4 Res
These are my Swordmaster!Wade's stats (replacing Cecilia), may I ask why they're so low? I will attach my log file, but I wanted to say I'm seeing a trend of characters just losing stats in spades after reclassing (see Swordmaster!Geese's (replacing Echidna) stats as well, maybe even Knight!Cecilia's as well?), just how is it possible that Wade has below class bases as base stats? What calcs is the randomizer doing with his stats based on my randomization settings that are causing him to have such low bases?
https://drive.google.com/open?id=1DoW0ZsN0SNeOllHaA_fTW9BVbevUajwk

**Comment by lushen124** [comment]
I'll look into it. I remember taking a few passes at this logic since it didn't look right to me in some cases. But in most of those cases, I was focused on prepromotes being demoted. It's possible that, since FE6's stats work differently on promotion, that I misplaced some stat points that should be there. (FE7 and FE8 have fixed promotion bonuses, FE6's promo bonuses are the difference in base stats between the unpromoted and promoted classes.)

**Comment by Lucky0426** [comment]
They could be low because Wade is a non-promoted fighter unit in the base game. Some units will always have low bases depending on their join time, level, and base class in the main game.
