### ISSUE TITLE
FE4: Some potential enhancements

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#191]
All addresses assume headered ROM. All of this stuff is from http://sheeda.himegimi.jp/olwen.html and there's more stuff, but it's either stuff that isn't particularly interesting for the randomizer, or stuff that I can't figure out due to the language barrier and not understanding this hacking stuff. All of these were tested by me to ensure they work as advertised.

Alternate mod to make holy weapons buy/sellable that retains the inability to sell the Circlet (use this instead of the other mod that makes holy weapons buy/sellable as this conflicts)

03F686: FF -> FE
04B4E4: FF -> FE

I believe this makes it so items of rank FE can't be sold instead of FF, since the first modification changes the rank of the Circlet from FF to FE. Holy weapons are rank FF.

Remove item 0x67 from being assigned to chapter 5 Ethlyn

1DC4E2: 11 00 67 -> 00 00 00

For the sake of completeness
1DC4E7: 11 00 02 Ethlyn ID 02 Iron Sword
1DC4DD: 06 00 3E Quan ID 3E Gae Bolg

The event plays out properly, and after it's done and you look at her inventory, she only has one item in her inventory (item 0x02). This will allow you to reclaim the unused item that you assigned to Nanna/Jeanne to fix the unknown inheritance thing issue, by allowing them to have item 0x67 again.

Pursuit skill not required to double

04E56C: 89 -> C9

Doubling threshold is still 1 AS, and I couldn't find anything about changing that. Apparently the routine for this stuff is at 04E135 ~ 04E169 and 04E553 ~ 04E57C. An interesting option, far easier to do than assigning every class the Pursuit skill to achieve the same thing.

Allow Seliph to inherit holy blood from bytes 3 and 4

0484C7: 19 00 03 -> 19 01 03

Note - this allows him to inherit Loptyr as well... changing any of those three bytes allows Seliph to inherit holy blood like every other child, but not changing any of those bytes and merely changing Sigurd's holy blood to something else still has Seliph "inherit" his normal bloods, ie. it is actually hard coded in vanilla. I'm not sure how to make it so he can inherit only the first three bytes, as opposed to the current rando method of only the first two, or this method to allow all four.

What does the randomizer currently do to allow Seliph to inherit other holy bloods anyway? I didn't find anything that works the way it does in it on this JP site.

Make Adept work with Brave weapons

04E4EC: 13 -> 00

Cool option, I guess.

**Comment by Hozu** [comment]
So after doing some experimentation, I found out that the game also has Seliph's 3rd and 4th holy blood bytes hardcoded set to 00. Which means it's possible to set his 3rd byte, and still exclude Loptous blood from being inherited form Deirdre, meaning that Sigurd can be assigned Thrud, Forseti, or Hezul blood without any issue (Bragi blood bad, although it wouldn't cause any gameplay problems as far as I know).

Here's a picture of the specific addresses in an UNheadered ROM (since that's what I was working with at the time): https://i.imgur.com/2CgLt6I.png

The red and orange boxes are the first and second holy blood bytes respectively, which you already change in Yune. The green and black boxes are the third and fourth holy blood bytes respectively, so you can modify the green box at $048373 (unheadered, or $048573 headered) to assign holy blood from the 3rd byte.

**Comment by lushen124** [comment]
That's interesting. It would be fairly easy to unlock Thrud, Forseti, Bragi, and Hezul for both Sigurd and Deirdre in that case. The only thing with Bragi is that Seliph has to spawn as a healer, which may not be great.

So just to make sure, does this still require the hex changes in the first post? Or do I just need to make sure I write the new blood flags to 0x48374 (Unheadered)?

**Comment by Hozu** [comment]
Only the changes in my last post, so only to 0x48374 unheadered. The other change will make it ignore what's set in those addresses for his holy blood, and do normal blood inheritance instead.

**Comment by lushen124** [comment]
To answer your question from earlier (and I apologize for getting back to this so late), Yune currently limits Sigurd and Deirdre's bloods to only Baldr, Naga, Dain, Njorun, Od, Ulir, Neir, and Fjalar. Since these only occupy the first 2 bytes, I simply directly write what his inheritance would be in the last step after all randomization has been completed. So if Yune made Sigurd a Sniper with Major Ulir and Deirdre a Duke Knight with Major Njorun (and minor Loptous), then I'd write 08 40 to the address you pointed out earlier, which would translate to Major Ulir, Minor Njorun replacing vanilla 06 00 (which translated into Major Baldr + Minor Naga).

It sounds like all we need is to unlock the other 4 bloods for Sigurd and Deirdre and then update the last step to also account for the third byte at the other address. So if we had, say, Sigurd with Major Od and Julia with Major Forseti, Seliph should have Major Od and Minor Forseti, so that would be (based on your illustration's colored boxes):

Red box: 00
Orange box: 02
Green box: 04
Black box: 00

**Comment by Hozu** [comment]
I did eventually figure out how you did it, when I did a file compare between a randomized ROM and a vanilla ROM, when looking near the address from the other hack I suggested earlier, which did lead me to figuring this new thing out. So that did work out nicely.

And yeah, your example sounds exactly like what would need to be done, and Seliph would not "inherit" minor Loptous from Deirdre because it's not set in the black box.

**Comment by Hozu** [comment]
Just did a quick test to ensure we both got it right, and yeah, we did. I did what you said and here we are: https://i.imgur.com/9z6HEot.png

Note that I left the holy blood for both Sigurd and Deirdre untouched.

**Comment by lushen124** [comment]
This is a bit late, but in testing the Pursuit thing, either I'm not completely familiar with the game mechanics, or this implementation might be incomplete? I had Azelle attack one of the chapter 1 bandits, and he couldn't double any of them, despite having an AS of -3 to the bandit's -11 AS. I can see it works for Naoise and Lex though.

**Comment by lushen124** [comment]
Ok, so I found out what was going on. After putting it through a debugger, what the change did was change the instruction from checking a single bit (for the Pursuit skill) to comparing to the aggregate skill value. Due to the SNES's CPU, the z-flag would be set if the bit check failed, which would branch away with the next branch instruction, skipping the follow-up attack routine. 

But when comparing full values, the z-flag would be set if the values matched exactly. Since most characters have more than just Pursuit, this check generally failed, so it would not branch away and continue to the follow-up attack routine. But if a character were to actually have ONLY Pursuit, as in the case of Azelle and Sigurd, they would actually pass the check, setting the z-flag and skipping the follow-up attack routine, thereby never doubling. This also explains why Alec was still able to double, since he had Pursuit AND Nihil.

For future reference, I recommend actually changing the following bytes from 00 40 to FF FF. This changes the instruction from `CMP #$4000` to `CMP #$FFFF`. This doesn't technically fix the issue, but it essentially checks to see if the character has ALL of the skills at the same time, which nobody should ever have. So the full change would be (on headered ROMs):

04E56C: 89 00 40 -> C9 FF FF
