### ISSUE TITLE
FE6 softlock if zeiss randomizes into a bard on chapter 16 (0x10)

### ISSUE THREAD

**Issue by Lord-Nightmare** [lushen124/Universal-FE-Randomizer#193]
If zeiss randomizes into a bard on chapter 16 (0x10), the game softlocks on npc turn 2 during his movement turn. Keizaron ran into this issue on stream, it was fixable by using FEbuilder to swap the zeiss-turned-allen-bard back into a wyvern rider with the stock weapons, at which point the game no longer softlocks.

**Comment by Lord-Nightmare** [comment]
I think this requires testing with all the randomizable characters on chapter 16 in place of zeiss, to determine exactly which ones need to be blacklisted from being swapped into that character slot, to prevent softlocking.

**Comment by Garlyle** [comment]
I had a softlock in the same chapter, but probably because my Zeiss carried a lockpick. Lockpicks on neutral/enemy units who can't use it will softlock the game.
For the record I had the same issue with Sue in Chapter 6, so it checks out.

**Comment by lushen124** [comment]
Interesting. I'll add something in to account for that. Thanks for the heads up. 👍

**Comment by Lord-Nightmare** [comment]
That explains a lot, the Zeiss in keizaron's game also had a lockpick, IIRC. I can pull up the savegame and check again.

**Comment by Lord-Nightmare** [comment]
Yes, that's exactly it. Zeiss-turned-allen had a Lockpick and an Elixir. So perhaps randomizing to a bard didn't cause the crash at all, just the lockpick?

**Comment by Lord-Nightmare** [comment]
This might mean the fix in https://github.com/lushen124/Universal-FE-Randomizer/tree/bugfix/0193-limited-recruited-characters-class-choices needs to be less stringent than it is. It needs further testing by forcing the units to those types and seeing if the game softlocks or not on an ai turn, I think.

**Comment by lushen124** [comment]
Yeah, in that case, I think the issue is more with why the randomizer is giving away lockpicks to non-thieves in the first place. My suspicion is that randomized recruitment and randomized classes is involved. I think they both individually handle thieves properly, but the combination of them might have left some lockpicks on units that shouldn't have them. I'll revisit this logic for the 0.9.2 release.

Please feel free to add further notes in #224 which I created to track the lockpicks issue.
