### ISSUE TITLE
FE4: Holy Blood shuffle overrides enemy blood restrictions.

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#194]
Example, someone had Eldigan with only Valkyria because Ares was a Priest with major Bragi blood.

Characters who share holy blood with enemies are Edain/Brigid (with Andre, and presumably Scipio if you use the option to force enemies to have holy blood?), Azelle (with Arvis), Tailtiu (with Reptor, Bloom, Ishtar, and Ishtore), and Lewyn (Musar, the three flying triplets in Endgame). All of them should be unable to have Bragi blood with Holy Blood shuffle option, and Azelle also needs a restriction on Ullur due to the Battle of Belhalla softlock if Arvis has a bow.

Lewyn is a special case, because Musar only has Forseti blood for gameplay reasons, and the flying triplets have no known reason that they have minor Forseti blood (not needed for gameplay, not stated in story).

**Comment by lushen124** [comment]
The current restriction is that no blood that is represented by a major enemy can be shuffled into Bragi. This currently includes Arion for Dain, Lombard for Neir, Arvis for Falajar, Reptor for Thrud, and Julius for Loptous. We can certainly make Eldigan the representative for Hezul instead of Ares, but I feel like there was a reason we matched Hezul to Ares.

As for restricting characters being unable to have Bragi blood, this should only matter if the said enemy has a legendary weapon, right? There are classes you can be that allow you to attack while having Bragi blood. It might just look weird to see a bunch of Valkyria staves around because of it. 

That said, adding more restrictions on this will start to make the option less useful, since we're not able to shuffle around too much after a certain point. Bragi is basically fixed on Claud at this point:

Baldr - OK (Only as of recently because we unlocked Sigurd's blood choices)
Od - OK (Might actually not be OK because of Chulainn)
Hezul - Eldigan (enemy boss)
Njorun - Altena (flying - can't use staves)
Dain - Arion (enemy boss)
Neir - Lombard (enemy boss)
Ulir - Andre (enemy boss)
Fjalar - Arvis (enemy boss)
Thrud - Reptor (enemy boss)
Forseti - Musar (enemy boss)
Naga - Julia (probably broken)
Loptous - Julius (enemy boss)

**Comment by lushen124** [comment]
Actually, I'll just remove Bragi from the pool entirely. Claud is just going to be stuck with it because there's too many ways for this to go wrong to allow Bragi to transfer anywhere.
