### ISSUE TITLE
FE6 capped stats reset

### ISSUE THREAD

**Issue by lukedunca** [lushen124/Universal-FE-Randomizer#195]
Sometimes when class changed characters cap a stat, that stat will reset to a zero upon the next level up. I've only noticed it with stats that hit 30 and it doesn't seem to happen with all the characters. Namely my Druid Chad had his resistance reset to zero after it had hit 30 and my General Allen had his defense reset to zero as well

**Comment by lushen124** [comment]
I believe stats in GBAFE are limited to 5 bits (maximum value is 31) which should be ok because no class should be able to go that high. I'm not sure why, but it seems FE6 has more than a few issues with stats being wonky. I'll investigate it to see if the translation patch has some weird things going on. One way to tell would be to play it in Japanese without the patch and see if there are still issues, but I imagine most people aren't willing to do that.

**Comment by lushen124** [comment]
Closing in favor of #196 since it seems to be the same issue.
