### ISSUE TITLE
FE9 Randomizer Thieves Issue

### ISSUE THREAD

**Issue by SuperSheikah** [lushen124/Universal-FE-Randomizer#204]
I believe this was also an issue on the FE9 Randomizer present on the FEUniverse board, but it looks like units randomized to thieves cannot open chests, though they can still steal and use knives properly. I have not yet gotten Volke or Sothe, but in the aforementioned randomizer those units were always able to open doors/chests, so there might be something funky going on there.

**Comment by lushen124** [comment]
Yeah, I had some reports for this because what happens is that IntSys added the KEY0 and KEY50 skills to Volke and Sothe personally instead of the thief class as a whole. I can make a fix, but I'm wondering if it's even worth worrying about randomizing thieves if literally anybody can open chests if given the skill.
