### ISSUE TITLE
[FE9] Mismatch Between Spoiler File and Actual Result for Mia

### ISSUE THREAD

**Issue by ClyncyeRudje** [lushen124/Universal-FE-Randomizer#214]
![GFEE01_2020-03-07_22-50-11](https://user-images.githubusercontent.com/61926732/76156320-ddd90580-60c6-11ea-86a8-78637ccd8bdc.png)
![GFEE01_2020-03-07_22-50-18](https://user-images.githubusercontent.com/61926732/76156322-ddd90580-60c6-11ea-8275-2d1f61a8cf3f.png)
As the title says, there was a mismatch between what the spoiler file output (Axe Cav w/ Daunt) and the actual result (appears to be a normal Mia-type Myrmidon with Daunt instead of Vantage despite her map model being a cav; her movement type, lack of canto, battle model, and weapons all match myrmidon. I'm playing with sound off so I cannot comment on what sounds she's using when she moves, but i'd suspect she's still using normal infantry sounds given everything else). 

I'm using Dolphin 5.0-11663 to run the randomizer.

My randomization settings are as follows:
-- | --
Randomize Growths | Redistribute (Variance: 30%)
Adjust HP Growths | NO
Adjust STR/MAG Split | YES
Randomize Bases | Redistribute (Variance: 5)
Adjust STR/MAG Split | NO
Randomize CON | NO
Randomize Affinity | YES
Randomize Skills | Randomize Existing Skills
Adept chance | NORMAL (4.62%)
Blossom chance | NORMAL (4.62%)
Celerity chance | NORMAL (4.62%)
Corrosion chance | LOW (3.08%)
Counter chance | NORMAL (4.62%)
Daunt chance | NORMAL (4.62%)
Gamble chance | NORMAL (4.62%)
Guard chance | NORMAL (4.62%)
Miracle chance | LOW (3.08%)
Nihil chance | NORMAL (4.62%)
Paragon chance | HIGH (6.15%)
Parity chance | NORMAL (4.62%)
Provoke chance | NORMAL (4.62%)
Renewal chance | NORMAL (4.62%)
Resolve chance | NORMAL (4.62%)
Savior chance | NORMAL (4.62%)
Serenity chance | NORMAL (4.62%)
Shade chance | NORMAL (4.62%)
Smite chance | NORMAL (4.62%)
Tempest chance | NORMAL (4.62%)
Vantage chance | NORMAL (4.62%)
Wrath chance | NORMAL (4.62%)
Randomize Playable Characters | YES
Include Lords | NO
Include Thieves | NO
Include Special | YES
Mix Races for Playable Characters | YES
Allow Cross-gender Assignments | YES
Randomize Bosses | NO
Randomize Minions | NO
Force Class Change | YES
Buff Minions | Flat Buff (+10%)
Improve Minion Weapons | NO
Give Minions Skills | NO
Buff Bosses | YES (Max Boost: 5 - Linear)
Improve Boss Weapons | YES (15%)
Give Bosses Skills | NO
Randomize Rewards | Randomize with Similar Items
Randomizer Seed Phrase | was ki ga endia van jenhah van ieeya van gyaje van parce van dsier van fane

**Comment by lushen124** [comment]
That... is interesting. This looks like the issue I had with Rolf where everything pointed to him being something else, but the game seemed to think internally that he was still an archer (going as far as using archer animations in battle, despite having a different class's map model). I thought this was strictly limited to Rolf, but it might be something else causing it.

Just curious, which difficulty are you playing on? And did she show up in Chapter 7 like this?

**Comment by ClyncyeRudje** [comment]
Yeah, the screenshots were from right after she was recruited. I'm playing on easy (since I wanted to get to later chapters as fast as possible for testing reasons), which I suspect may be a factor? I know Easy can cause issues on other games.

I haven't gotten much further in the game so I haven't been able to test her promotion but I wouldn't be surprised if she becomes a Swordmaster.

**Comment by lushen124** [comment]
I ask because I noticed some weird quirks between Normal and Hard. Things like Ike's skill not actually being applied without assigning it in the prologue (as opposed assigning it in the character data). Hard seems to be where most things just work, but it's also quite a bit more challenging to test, especially if you do what I do and give every minion a random skill, or if you just get some less than capable classes.

**Comment by Bryan064** [comment]
I saw this comment so I figured that this was related.
I'm using the 0.9.1 Release and I ran into the same issue. My Mia wasn't randomized. However, I am playing on hard mode.
The Changelog says that She should have been a Wyvern Rider with Vantage.
Also, While I was playing with randomized rewards, all the chests in the chapter are not Randomized as well. I got Armor Slayer, Ward and Miracle scroll. 
![image](https://user-images.githubusercontent.com/62855581/77860615-0f745680-71c5-11ea-8f07-2624d40ee8e4.png)
![image](https://user-images.githubusercontent.com/62855581/77860620-126f4700-71c5-11ea-9039-19412233944a.png)
This is all fantastic, though! I know practically nothing about coding but if you need any more info or play testing, let me know!

**Comment by lushen124** [comment]
Interesting. I had assumed Hard Mode was the least problematic, but that may be wrong. It sounds like certain characters are just not being set appropriately. I already know Rolf is in a similar boat, which is why he doesn't normally get randomized (in a similar fashion, he's always forced to being an Archer, no matter what class he's actually assigned). My most recent test wasn't a great seed because I got a male myrmidon for Mia, which obviously wouldn't highlight any issues. It's also in Ch. 7, so testing it becomes tedious having to play that far. I'll have to write a special editor to make modifications to test things, instead of organically doing randomizations.

As for Ch. 7's chests specifically, this is actually a known issue. I don't fully understand the chapter script yet, but I do know enough to change items that are given in a very crude way, more or less assuming a series of bytes that lead up to a pointer to an Item ID. Ch. 7's chests do not follow the same byte series as the other chests in the game, and it only leaves 1 byte for a relative address jump, as opposed to the usual two bytes, so it's very limited in terms of repointing. My next step for FE9 is to really dive into the chapter script, both to do random rewards properly, but also to see if there's anything weird in there forcing classes beyond what the character data says. I suspect there has to be something forcing stats and classes to be something different than the character data specifies, because it's only for certain characters.
