### ISSUE TITLE
[FE4] Ethlyn only has a certain class pool that cannot be changed from Troubador, Cavalier, Axe Knight, and Lance Knight

### ISSUE THREAD

**Issue by nero4555** [lushen124/Universal-FE-Randomizer#228]

**Comment by nero4555** [comment]
my bad I know whats happening you can close it

**Comment by nero4555** [comment]
I know its supposed to help softlocking, but I think the chances of getting another mounted unit are very high, so why not just make it a part of retain horseback units?

**Comment by lushen124** [comment]
We could, but I'd rather not take that chance because there are a lot of classes for both Quan and Ethlyn could feasibly survive the Horseslayers (probably not the Gungnir, but nonetheless). Mounted units also include two flying units, which are much more likely to cause issues, which is why it doesn't piggy back off of retaining mounted units. I'll leave the idea open though.
