### ISSUE TITLE
FE9: Gatrie and Shinon Rejoin weapons

### ISSUE THREAD

**Issue by karavalenge** [lushen124/Universal-FE-Randomizer#233]
In FE9, Gatrie and Shinon have a Steel Lance and Brave Bow when they rejoin in Chs 13 and 20 respectively, regardless of what class they are. This can end with them being permanently declawed if they are Laguz.

Shinon specifically loses the weapon he starts ch 20 with since to recruit him you have to defeat him and the weapon is tagged as droppable. I'm unsure of how you could replace his weapon if he's a Laguz when he joins in ch 21 preparations.

**Comment by lushen124** [comment]
I see IID_STEELLANCE explicitly mentioned in the Chapter 13 script and I see IID_BRAVEBOW explicitly mentioned in the Chapter 18 script, so I'm guessing those can be modified like I do to the randomized rewards. The only weird thing would be Shinon dropping a fang in that case. But yes, I'm pretty sure I can replace their weapons in the script. I just want to figure out and understand the script first instead of blindly changing the item without understanding the script (considering there's a lot of other things I suspect the script is interfering with).
