### ISSUE TITLE
FE9 Crash on Wii

### ISSUE THREAD

**Issue by AmbiguouslyAnonymous** [lushen124/Universal-FE-Randomizer#249]
I noticed that whenever I try to load the randomized ISO on my Wii (using Nintendont) the screen goes black after showing the publishers and wont do anything more (I assume it happens when it tries loading the intro movie). The same ISO runs just fine on Dolphin on my laptop, and Nintendont doesn't have any problems with any of my other GameCube ISOs so I'm assuming it has something to do with the randomizer.

**Comment by lushen124** [comment]
Interesting. I'm wondering if there's something I'm missing when rebuilding the ISO. The stable 5.0 version of Dolphin (which is almost 4 years old now) runs this fine, but there's actually issues with the more recent development builds of Dolphin. It's possible that 5.0 Dolphin was more lax with some requirements that have since then been resolved to match closer to actual hardware (or maybe closer to a Wii than a Gamecube). I can look into it, but I can believe that some part of the ISO is not correctly rebuilt to be read properly.

![image](https://user-images.githubusercontent.com/1689159/81354994-eb3c4d00-9081-11ea-90cb-5ae22ae852fd.png)

That's what the newest version of Dolphin gives when I try to run a randomized game. Surprisingly, Dolphin continued to run after the error, which wasn't the case for other dev versions. But I suspect that error may be sufficient to halt execution on an actual console. I'll have to look into it more and see what that error actually means.

**Comment by lushen124** [comment]
I was going to tackle this for 0.9.2, but while I've managed to get it past the title screen. There are some quirks to what a real hardware requires and what Dolphin will let you get away with. I still need to work out some of these quirks out, but there are a few leads. I'll bump this to 0.9.3 and prioritize it there, but there are a lot of other changes in 0.9.2 already that I want to get out.

**Comment by MichaelPowney** [comment]
I'd love to play randomized FE9 on the Wii. Any chance we could use DiscEx files with the randomizer?

**Comment by sergiodaviduo** [comment]
For the record, I've been playing my copy of FE9 on my wii using Nintendont just fine, on chapter 8 right now. Using an emulated 251 block memory card, iso and save file are on usb drive.

Attached is my configuration log:

[Fe PoPYS log.html.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/5468609/Fe.PoPYS.log.html.zip)

**Comment by lushen124** [comment]
That's weird, because I couldn't get very far at all on real hardware. I made a few changes to get a bit further, but it always crashed right after the prologue's title card for me.

**Comment by sergiodaviduo** [comment]
interesting....

I have an original 2007 wii, maybe that's a part of it??? Let me know if there's any debugging I can do on my end. I'm also super curious if I can get it to work again by launching back into a suspended save after the cutscene (getting there via an emulator). In any case, I'll try launching via an SD card and maybe another USB device if that's related?

**Comment by AmbiguouslyAnonymous** [comment]
Alright so, since I had nothing better to do today I decided to test out the randomizer today on an actual Wii again (Old 2007 Wii, using Nintendont).

I randomized the same starting rom 6 times using the exact same settings and got differing results. It crashed before even loading the opening cutscene for three of them, but the other three actually all made it to the tutorial. Two of them crashed when trying to load the Chapter 1 cutscene, but the other one actually managed to play all the way to Chapter 9. 

From the looks of it, the one that got the furthest crashed when it tried to load in Rolf appearing on the map. (I'm only guessing this since normally that chapter would be the first time you see him using his Archer model instead of his Child model.)

Additionally, I noticed that if I loaded saves from a vanilla game onto a randomized rom, I could actually load the later chapters just fine, albeit everyone uses a blackened version of Ike's model. (I haven't tried playing through said chapters that way though, only loaded them to see if it'd immediately crash or not)

Not sure if any of this is helpful, but figured I'd share anyway. I'm not sure why it crashed before even the title loaded for me those few times, but it seems to me most of the crashing has to do with characters' models.
