### ISSUE TITLE
Ike cannot use Regal sword or Ragnell as lord

### ISSUE THREAD

**Issue by puneet1999** [lushen124/Universal-FE-Randomizer#250]
On the Black Knight chapter and Ragnell is greyed out.
Only possible way to defeat the black knight is using A/S weapons which is working as intended

![image](https://user-images.githubusercontent.com/59244280/81991829-f39f0580-95f6-11ea-84c3-9468cf9cbc4a.png)

**Comment by puneet1999** [comment]
But if Ike is a ranger, he can use regal sword and Ragnell 
![image](https://user-images.githubusercontent.com/59244280/81993898-8b065780-95fb-11ea-8ff3-4ee9c90171b4.png)

**Comment by lushen124** [comment]
Ah, good catch. I forgot to add logic for to allow character classes to have skills added. I'll have a fix in the next version. Ranger works because I replaced the skill that forces its Ch. 17 promotion with one to allow Ragnell/Regal Sword to be equipped. Lord didn't have a skill to replace, so it just didn't work.

I'll have a fix in the next version. #252 addresses this.
