### ISSUE TITLE
Paragon skill from randomized house weird interaction IID_ELITE

### ISSUE THREAD

**Issue by puneet1999** [lushen124/Universal-FE-Randomizer#251]
Got to chapter 24 and got Paragon skill from a randomized house. It's not usable and has IID_ELITE as its name. Screenshot below

EDIT: As i went further in the game i found a weird interaction. Astrid can only use the IID_ELITE skill which is weird since typically thats her normal skill she comes with. Maybe the game locks the skill just for her? A good bug if fixable.

![image](https://user-images.githubusercontent.com/59244280/82095632-468ac280-96b4-11ea-8e26-68047fc48298.png)
![image](https://user-images.githubusercontent.com/59244280/82095637-48ed1c80-96b4-11ea-93f0-ca9a8089ade7.png)
![image](https://user-images.githubusercontent.com/59244280/82095716-789c2480-96b4-11ea-8b37-9a7f1996a4c5.png)

**Comment by lushen124** [comment]
Ah, this is interesting. I saw some stuff in the skills data that seemed to have a lock for Paragon to Geoffrey, but I didn't see anything that would lock it to Astrid. As for the "IID_ELITE" that's the internal name for a Paragon scroll, which is obviously unused. Surprisingly it doesn't have a name for the scroll, but that's easy enough to add.

The other scroll that would be slightly interesting would be Blossom, which the skill data specifically lists it being for Sothe (which makes sense).

That said, I did find some stuff after the skills table that may hint at usability, since it has IID_ELITE, followed by PID_GEOFFRAY and PID_STELLA (Stella being Astrid's JP name). I'm not entirely sure how that data is structured, but I could try removing both names and seeing if that has an effect. They seem to be restrictions, either to PID (character) or JID (class). Like a hypothetical skill scroll for Galdr chant is locked to Herons. Most skill scrolls don't have anything listed and just immediately follow to the next skill scroll. But if this table is to be believed, the occult scroll is somehow restricted to Sages and Bishops.
