### ISSUE TITLE
FE4: Weapon Assignment Stict/Loose Sidegrade not Working

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#254]
This is just the first example that comes to mind, but I am sure I saw many similar cases in past randomization attempts and maybe a couple more can be found in this very same randomization attempt, but: I randomized two roms with the same options (most notably randomized playable characters, randomized holy bloods and adjusted conversation gifts), the only differences being that weapon assignment was set to Loose in one randomization and Strict in the other (also randomized shops, but I don't think that should have any effect and it was mostly for fun).

 In both attempts Deirdre was a Bow Knight (with Major Ulir) and came with a Steel Bow (rank B) and a Brave Bow (rank B). Deirdre originally comes with an Aura tome (rank A) and a Silence staff (rank B). As far as I understood it:
- Loose Sidegrade should have given her a Silver Bow (A-rank equivalent to Aura) and either a Steel Bow or a Brave Bow (B-rank equivalents to the Silence staff)
- Strict Sidegrade says characters are given "the closest counterpart to the original weapon if possible where possible, otherwise fall back to Loose Sidegrade"; maybe Brave Bow and Steel Bow are in fact considered the "closest counterparts" to Aura and Silence, but if they are may I ask why? And if they are not, well then I fear Strict Sidegrade is not working properly either.

  Also, it's unclear to me whether this Strict/Loose Sidegrade also applies to the "Adjust Conversation Gifts" options. Because I think it would be neat if it also applied to items obtained through events; if it's supposed to already apply, then it is not working for that either: Lex is a (lance) Armor with Minor Dain (so he has A rank lances) and in both randomization attempts his vanilla Brave Axe was randomized into not a Brave Lance but a Silver Lance. I attach the logs of both attempts.

https://www.dropbox.com/s/ziqyoi69f2qplv7/Loose.html?dl=0
https://www.dropbox.com/s/ysd2wn49znlttwp/FE4R.html?dl=0

**Comment by lushen124** [comment]
The options should mostly be independent of each other so strict sidegrade only applies to the class randomization and not conversation gifts (though this could be changed).

As for the strict vs loose sidegrade: Loose simply matches the rank while strict has a few more heuristics based on the set the original item is in. Aura is classified as a "Silver" weapon, an A rank weapon, and a "powerful" weapon. This would mean Aura should be replaced with a silver-grade weapon. 

What I'm guessing happened is that Aura's slot is special. In order to fix a glitch in gen 2 where Aura could be duplicated, We changed Deirdre's inventory ID to use 0x34 (it's normally 0x60, which is the item that Seliph gives to Julia in Ch. 6), which is an unused Steel Lance in gen 2. Since Steel Lance is B rank, it's probably a matter of doing things out of order. Instead of using Aura as the reference item, it's using Steel Lance, which would explain the Steel Bow being the closest equivalent.

So what happened was:

Silence (has no strict classification, so falls back to loose) -> Brave Bow (both B rank, which is correct)
Aura (incorrectly classified as a Steel Lance) -> Steel Bow (which would be correct if it actually were a Steel Lance).
