### ISSUE TITLE
FE9: Gatrie and Lethe experience bugged growth mechanics

### ISSUE THREAD

**Issue by AugmentedAntics** [lushen124/Universal-FE-Randomizer#255]
So, recently, I decided to do a run where everyone has 99%-100% growths just for fun.  However, Gatrie and Lethe seem to be the only units that don't apply to this. Even though the changelog says they have 99%-100% growths like everyone else, they continue to get hardly any stat increases when gaining levels. At first I thought they missed their 99s, but even their 100s don't always increase on level-up.

Lethe also seems to be a bizarre case. The changelog says her randomized skill is Paragon, but when she joined, she didn't have a skill at all.

**Comment by lushen124** [comment]
Gatrie is a new one. Lethe is a known issue, as there are a lot of issues with her character data, which doesn't seem to be applied with the existing code. I'm looking into that right now, but the fact that it doesn't apply to Gatrie is interesting, because I know at least he can properly change classes (whereas Lethe cannot). 

Thanks for the report. 🙂
