### ISSUE TITLE
FE8 bug: Sprite display glitches

### ISSUE THREAD

**Issue by sbeach** [lushen124/Universal-FE-Randomizer#258]
Chapter 20 (Darkling Woods) sprites appear different on map than the actual unit. Some enemies are represented by a piece of Morva's sprite, while others are represented by an entirely different class. Even worse, units are sometimes simply not shown on the map at all.

These observations were made during the preparations for the chapter, specifically while viewing the map with "Formation".

Hero (tiny piece of Morva wing)
![20200705_FE8-heroMap](https://user-images.githubusercontent.com/3373887/86540880-ce7b9480-becd-11ea-95d2-9db886ad169e.png) ![20200705_FE8-heroUnit](https://user-images.githubusercontent.com/3373887/86540881-ce7b9480-becd-11ea-8f20-6d4da30ff2bd.png)

Wight bow (shown as Wyvern Lord)
![20200705_FE8-wight1Map](https://user-images.githubusercontent.com/3373887/86540886-cf142b00-becd-11ea-9eb0-2d01e911c5c7.png) ![20200705_FE8-wight1Unit](https://user-images.githubusercontent.com/3373887/86540887-cf142b00-becd-11ea-992e-8796ff9dfa65.png)

Druid
![20200705_FE8-druidMap](https://user-images.githubusercontent.com/3373887/86540878-cde2fe00-becd-11ea-9423-e85fadd9be87.png) ![20200705_FE8-druidUnit](https://user-images.githubusercontent.com/3373887/86540879-cde2fe00-becd-11ea-9f4f-19542b788b0c.png)

Pupil
![20200705_FE8-pupilMap](https://user-images.githubusercontent.com/3373887/86540882-ce7b9480-becd-11ea-95c9-01a4f959fd75.png) ![20200705_FE8-pupilUnit](https://user-images.githubusercontent.com/3373887/86540883-ce7b9480-becd-11ea-9232-bc168c15d5a6.png)

Sniper
![20200705_FE8-sniperMap](https://user-images.githubusercontent.com/3373887/86540884-cf142b00-becd-11ea-8690-e05e451ed6cd.png) ![20200705_FE8-sniperUnit](https://user-images.githubusercontent.com/3373887/86540885-cf142b00-becd-11ea-84f3-d618c55ef8c1.png)

Wight (sword)
![20200705_FE8-wight2Map](https://user-images.githubusercontent.com/3373887/86540888-cf142b00-becd-11ea-91db-d6438587fba6.png) ![20200705_FE8-wight2Unit](https://user-images.githubusercontent.com/3373887/86540889-cfacc180-becd-11ea-897f-649b8f028ac0.png)

**Comment by sbeach** [comment]
ZIP with game save data
[spriteGlitches.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/4875478/spriteGlitches.zip)

**Comment by sbeach** [comment]
I'm now on turn 3 of the chapter and the sprites have returned to normal.

![20200705-turn3snip](https://user-images.githubusercontent.com/3373887/86541309-6fb81a00-bed1-11ea-9a9d-dc9a6650a71b.PNG)

**Comment by sbeach** [comment]
Turn 4, eyeball reinforcements arrived and the sprites exploded again. This time one of my own units were included; my Swordmaster displays as mostly-a-gargoyle.

![20200705-turn4snip](https://user-images.githubusercontent.com/3373887/86541540-53b57800-bed3-11ea-8ca6-ab1cf8fbe569.PNG)  
![20200705-turn4snip-amelia](https://user-images.githubusercontent.com/3373887/86541539-531ce180-bed3-11ea-8e2c-aeb2afcd25ee.PNG)

**Comment by sbeach** [comment]
I stopped documenting, but the sprites eventually returned to normal after another turn or two.
Could this issue be due to the abundance of sprites on the map?

**Comment by lushen124** [comment]
This is my guess. I know that there are some issues with having too many sprites on screen, where the game will overwrite some of the sprites with other sprites. I remember some sprite oddities back when I was creating new weapon icons, where there's an image cache that limits the maximum amount of weapon icons available to be supported. This isn't about weapon icons, but I suspect there is also a limit specifically on **types** of sprites on a map. 

Specifically, this probably only happens if you randomize minions, and there's enough enemies on the map with a wide enough array of classes that it overloads the sprite cache.

The solution, either only for this map or just in general, could be to change all enemies of one class to a different class when randomizing minions. So all Arch Mogalls randomize together into, say, Falcoknights.
