### ISSUE TITLE
FE4: Item 0x2 is not being randomized; item 0x67 potential issue

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#26]
Both items 0x2 and 0x67 are given to Ethlyn in chapter 5 when she's a green unit. In the vanilla game, 0x2 is an Iron sword, and it ends up being inherited by Leif. Item 0x67 is a Mend staff, and does not get inherited. However, that item is added to the starting inventory of Nanna/Jeanne, so if Leif is able to inherit it, I'm not quite sure what will happen. It might end up removing it from the inventory of Nanna/Jeanne, or it might appear twice and have glitchy behaviour.

**Comment by lushen124** [comment]
I do wonder if Leif's inventory is just special in that regard. I don't know if Ethlyn's inventory from Chapter 5 passes down the same way as other children or if Leif's inventory is just specially set. Can we test this specifically before we make a change? The solution will be a bit interesting too, since I'm not quite sure what to do here. 0x67 is hard coded onto Nanna, so she will definitely get the item. It's only a question of whether Leif will potentially take it too.

**Comment by Hozu** [comment]
I can change item 0x2 to something Leif can inherit and see what happens when I get to that point. Or are you wanting me to check item 0x67?

**Comment by lushen124** [comment]
I guess I'm still trying to figure out who 0x2 and 0x67 should actually belong to and assigned for. My gut says that it should be assigned to Leif and Nanna, respectively, but then that might break Ethlyn when she shows up? Then again, without battle animations for NPCs, that may not be an issue.

So there's one question and one potential issue right now. The question is whether Leif gets 0x67 if he can use it (which would cause both Leif and Nanna to get the same item). The potential issue is that 0x2 needs to be handled in a special way since there's no link for 0x2 otherwise (it's not hard coded to anybody's inventory, despite us knowing it shows up in Ch. 5 Ethlyn and Leif's starting inventory).

**Comment by Hozu** [comment]
Now that I think about it, could you just not have Ethlyn be assigned item 0x67 in her chapter 5 appearance? Is that even possible? There doesn't appear to be a Nightmare module to modify those instances of them, and their item assignment is probably scripted.

I haven't got to the point to see if Leif would inherit item 0x2 yet, but I already changed it to an item that he would inherit and it does change the weapon in Ethlyn's inventory. If he's able to inherit 0x2, he'd definitely be able to inherit 0x67. From what I can tell, the latest item assignment is what ends up being kept on a reset, so both Leif and Nanna/Jeanne would have 0x67, but save + reset would remove the item from Leif's inventory.

The only map battle animations I've come across that actually break the game (other than ch 5 bow Arvis) is a Dracoknight with a tome.

**Comment by lushen124** [comment]
I have no idea how Ethlyn is getting inventory item 0x67 (or 0x2 for that matter) right now. Honestly, I don't even know if she has item 0x67 because enemy and NPC items normally aren't tracked as real items (i.e. inventory items). The question also is, if I change weapon 0x2 and 0x67, does that change what Ethlyn carries? Or did we assume that step?

**Comment by Hozu** [comment]
Changing 0x2 and 0x67 does indeed change what Ethlyn has. And they are definitely real items, as evidenced by selling Quan's holy weapon in chapter 3, and having it disappear when doing a save and load while NPC Quan is there with the weapon. Presumably the copy you kept won't be lost when Quan has his weapon removed, but I didn't test that because it's not entirely helpful to know.

**Comment by lushen124** [comment]
So then we can just give Quan in Ch 3 another weapon to mirror his so that, if he were to sell it, it would end up somewhere else in Gen 2. The vanilla Gae Bolg would be shared between Quan’s Ch. 5 appearance and Altena alone.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hozu** [comment]
Er, the Altena thing is part of the other issue, but... If you can have the event give a weapon other than... 0x3E (I think that's the vanilla Gae Bolg?) to Quan, that would fix the one issue. There is another issue that will pop up if you do that though - if you don't sell the holy weapon obtained in chapter 3, Altena will inherit it, and the one she starts with will end up going... I'm not exactly sure. Theoretically, the two instances would trade places, which is what happens in vanilla if you do something like... having Arthur inherit Wind (Arthur gets the inherited Wind, while his starting Wind is put into the ch 8 shop where the inherited one would have been). But I'm not sure if that's a hardcoded thing that happens with only items that are the same kind in vanilla (ie. the two different Wind tomes), or is a generic thing.

However, I came across a different potential issue that I didn't know about - a unit can inherit multiple copies of the same weapon, if the parent has them. It's different from inheriting the same item as the starting weapon, which causes the unit to have only one copy rather than two.

What this means is, if Quan doesn't sell his holy weapon in chapter 3, and one doesn't have Quan lose his holy weapon in ch 5 by event, I believe Altena will start with two copies of it due to inheriting both. But I have not reached the point where I can confirm that Altena does inherit ch 5 Quan's holy weapon if you skip the event that causes NPC Quan to lose it. (ie. I got to the part where I skipped him losing his weapon, and I removed it as a starting item from Altena so if she has it when I reach chapter 8 it will be by inheritance) But her starting with both copies is less of an issue than potentially one disappearing for good.

**Comment by lushen124** [comment]
Oh, I replied to the wrong bug lol. The two are somewhat related, but to come back to 0x2 and 0x67...

We can fix 0x67 by just making that mend staff something else other than 0x67 (though we'd be losing an inventory slot to do so (or we put 0x67 in a shop like we did with Aura)). Actually, I just realized 0x67 is already a shop item?  This makes no sense for vanilla. It's a weapon that's hard coded to a gen 2 character (both Jeanne and Nanna), yet it's also listed in the Chapter 8 shop?

But since that's the case, we can use another item slot to represent Jeanne/Nanna's starting Mend staff and if Leif can use 0x67, then great, he gets the item by inheritance. If he can't then it shows up in Ch. 8's shop already anyway. The only downside is that we lose another one of our limited item slots.

0x2 is definitely not getting touched right now because nobody has any reference to it. We could make it an exception and assign it explicitly to Leif in Gen 2 (with the only downside that Ethlyn might end up with an arbitrary weapon in Ch. 5).

**Comment by Hozu** [comment]
Nanna/Jeanne are one of the few gen 2 characters who get two starting items, the other being Fee/Hermina. She gets ...some sword and a Mend staff. I like the shop idea, probably put 0x67 in the chapter 8 shop instead, since there's probably a free spot there. I don't think there's a spot in the ch 7 shop that's free. If there was, it would probably be safe because if Leif were to inherit it, I imagine it wouldn't show up in the shop because if Ced exists the Light tome isn't in the ch 8 shop despite Ced appearing partway through the chapter.

> Actually, I just realized 0x67 is already a shop item? This makes no sense for vanilla. It's a weapon that's hard coded to a gen 2 character (both Jeanne and Nanna), yet it's also listed in the Chapter 8 shop?

This may have something to do with allowing the staff to still exist if Nanna/Jeanne died in ch 7, I guess.

**Comment by Hozu** [comment]
I've done a bit of thinking, and I think it might be beneficial to ensure item 0x67 is some kind of staff, unless Leif can inherit staves. If he can, make it something that he can't inherit, but ideally something that Ethlyn can wield. Although, since that isn't possible with certain children class matching options, then it would have to be something that neither can wield while unpromoted as a last resort. Unless you don't care if Leif can inherit item 0x67 as well, I suppose.

I say staff as the first choice simply because Ethlyn can't counter with it, and healing items are nice to have available.

But yeah, randomize item 0x2 explicitly for Leif, and ideally have it prioritize being a weapon type that Ethlyn can use as well. If their classes make that not possible, it would have to be something Ethlyn can't use.

**Comment by lushen124** [comment]
Ethlyn isn't guaranteed to be able to use staves, but I think it's safe to say that 0x67 would have to be a weapon Ethlyn can use since she's the only one that has any ownership of it after I remove it from Jeanne/Nanna.

And 0x2 will attempt to be a weapon that both can use Ethlyn and Leif can use, but in the case that they have no overlap of weaponry, then it'll defer to being for Leif.

**Comment by Hozu** [comment]
I suggested a staff for 0x67 not because Ethlyn can use it, but because she can't use it in most cases. That is, it's better to have an unusable staff over an unusable other weapon, simply because the AI won't use the staff, to my knowledge.

**Comment by lushen124** [comment]
So are you suggesting to always make it a staff, regardless of Ethlyn's class? Because we can just keep it a Mend staff if that's the case. Since it won't be attached to anything once I change Jeanne/Nanna's inventory, it just won't be changed beyond that.

**Comment by Hozu** [comment]
Yeah it can be left as a Mend staff if you want. Might as well make it the best C level staff.

By the way, I finally reached the point where I can confirm that Leif does inherit item 0x2 if he can equip it.

**Comment by lushen124** [comment]
I assume 0x67 follows the same rule?

**Comment by Hozu** [comment]
I didn't explicitly check that, but it's safe to assume that's the case. Both 0x2 and 0x67 are given to Ethlyn, and that can be seen by changing what those two items are and loading the save. ie. she definitely gets the actual items.
