### ISSUE TITLE
FE4: Altena promoting into a class with a different mount despite not enabling "allow mount change" option

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#28]
Seed details [here](https://www.dropbox.com/s/v90p5zy17pa6bw7/FE4%20rando%2052.html?dl=0). This changelog is the same as in other issues.

**Comment by lushen124** [comment]
Hmm... looks like the option to match children is interfering with Altena. This was put in place so that Coirpre would promote into the same class Claud was to ensure his weapon was usable, but since Altena doesn't have a real analogue in Gen 1, I used Quan instead. Maybe she can get by without a real analogue to match.

**Comment by Hozu** [comment]
Quan is already limited to a class that ensures he gets a holy sword or lance, so as long as Altena is limited to Pegasus Knight and Dracoknight she doesn't actually need an analogue.
