### ISSUE TITLE
[FE9]: Yune randomizer 32-bit stuck indefinitely halfway through randomizing process

### ISSUE THREAD

**Issue by Redshhift** [lushen124/Universal-FE-Randomizer#281]
I am on a 64 bit system, but Yune 64-bit crashes on startup after less than half a second.  32-bit Yune works fine until its processing the randomization.  It will seize up at this process : Recalculating file offsets... (/zbg/map12_harbor01/bf.cm
I have tried it multiple times and always gets stuck here.  I left it on overnight and found it in the same spot this morning.  Any ideas would be appreciated.  
As a note, I have zero technical insight to how emulation or randomizing works and limited knowledge of programming/ computer architecture in general so I may need specifics on ways to solve this if its not too much to ask.  
Thanks :)

**Comment by lushen124** [comment]
If you can't run the 64-bit one but can only run the 32-bit one, that's a sure sign that your machine actually is running a 32-bit JRE. 32-bit JREs tend to have this issue because their default memory limit is usually not set to be high enough to process FE9. For what it's worth, it IS possible to have a 64-bit system, but still be using a 32-bit JRE, however confusing that might be.

There are ways to verify and rectify this, but if you want the simple solution, I recommend just updating your JRE to a 64-bit version. The one I use for testing is here: https://www.oracle.com/java/technologies/javase-jdk14-downloads.html. Pick the one for your operating system and install it, and make sure you download and run the 64-bit version of Yune, because the 32-bit version will not run anymore once you install this.

Let me know if you continue to run into any issues.

**Comment by Redshhift** [comment]
Ok, got the 64-bit running and randomized my game.  If I find any problems in game later on I'll let oyu know.  Thanks so much!
