### ISSUE TITLE
FE4 Children Randomization Issue

### ISSUE THREAD

**Issue by SandHorse467** [lushen124/Universal-FE-Randomizer#285]
When choosing to randomize the classes of the children, their new class will always match the original one in weapon usage. For example, Arthur will always use some kind of magic, lester will always use a bow, seliph will always use a sword, etc. Their promoted classes can be made completely random like any other character, but their base classes will always have the same weapons. Having them match their parents' classes works properly, though.

**Comment by lushen124** [comment]
Hmm... Maybe I'm not understanding properly, but what's the issue? The options under the Children class randomization allow for any of the three you mentioned, which from top to bottom are, Strict Matching to Parents (Children will be the same exact class as their gen 1 counterparts), Loose Matching (Children will be a class that uses the same weapon types as their gen 1 counterparts), and Random (exactly what it says).

Is loose matching broken? Do you see children that don't share the same weapon type with that option enabled?

**Comment by SandHorse467** [comment]
Loose matching and strict matching are fine, the Random option is the one that I am having trouble with. If the Random option is selected the class that a child gets will always share a weapon with whatever their original class was. If we look at Arthur, should he always be some kind of mage, or should he be able to randomize into a class that uses swords, axes, or lances? Sorry for not making this clear in my original post.

**Comment by lushen124** [comment]
Ah, I see. I had to look over the logic again, since it's been a while. It does look like, for whatever reason, even in the Random case, I set it to require the same weapon. I'm trying to remember if there was a reason I did that, but I can't see why I did that for the completely random case. Might have been an instance of copypasta. I'll put in the change to not restrict the class in the Random case. Thanks for the report!
