### ISSUE TITLE
FE4: Growth rate of a stat can exceed the maximum limit set in absolute growths option

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#30]
Seed details [here](https://www.dropbox.com/s/v90p5zy17pa6bw7/FE4%20rando%2052.html?dl=0). This changelog is the same as in other issues. This happens to Julia every time (I did not randomize Julia), but it can happen to other units as well. I also saw it on Quan's SPD growth rate when looking quickly for a unit who has the problem.

Although, if the maximum growth rate is limited to below 60, how would that interact with major holy bloods that give +60 to a single growth rate?

**Comment by lushen124** [comment]
I don't take into account holy blood growths when determining range, so yes, you could get 85% + 60% from major blood, but I can't really stop that (outside of perhaps limiting the holy blood growths to no more than 20% in any single area, doubled for major blood).

**Comment by lushen124** [comment]
Also, Julia's randomization restriction only applies to class randomization. Randomizing her bases or growths are fair game. Class randomization is the only one where she can lose Naga blood, so that's why that one is restricted. Not randomizing Julia is not a global restriction. Holy blood changes are strictly additive, so she can't lose Naga there either. The most that can happen is that Naga's +80 stat boost is allocated suboptimally for facing off against Julius, but I think negating Loptous is the most important (and maybe making sure she has Nihil too).

**Comment by lushen124** [comment]
Just to make sure, are you only exceeding the limit in growths because of holy blood? Because if so, that's actually intentional. With holy blood, a full randomization restriction is impossible for smaller ranges, so I don't take holy blood into account with growth randomization.

**Comment by Hozu** [comment]
Yeah it's only from holy bloods. Since that's intentional, I will close this issue.
