### ISSUE TITLE
Option to stop gender bending? 

### ISSUE THREAD

**Issue by Hotgemstone** [lushen124/Universal-FE-Randomizer#316]
I'm finding it somewhat immersion breaking that when randomizing classes on the GBA male And female characters become genders swapped classes. Ninian becoming a brigand, and Hawkeye becomes a female Bishop for example.

I find this detail a strange omission because I believe it was present in the previous GBAFE randomizer you made. But in that one you can't randomize enemies so I can't really create the experience I'd like to have. I've tried using both (class randomization by GBAramdomizer and Yune for enemies and bosses, but that just breaks the game. 

If you have some time and  wan to  Help a total stranger I'd really appricoate it! %

**Comment by lushen124** [comment]
I'm looking to add it back in. It's a fairly common ask at this point, and it wouldn't be too hard to do. The reason I removed it initially was because this randomizer started with only FE7, and FE7's female class selection is pretty lacking. Specifically Lyn only has three options total: Pegasus Knight, Archer, or Mage. The other female classes cannot attack which would softlock prologue. That said, the games I implemented afterwards have far better options, so it makes sense to add it back in as an option.

**Comment by Hotgemstone** [comment]
Alright, thanks for letting me know! ☺

**Comment by Hotgemstone** [comment]
I'm still hoping this feature will be implemented at some point! 😛

**Comment by johnnyq3** [comment]
This would be an amazing feature.  With FE8 there is a greater distribution of female classes, too bad there isn't a way to port or back port the classes to the other GBA games.
