### ISSUE TITLE
FE4: Static character was assigned both a major and minor holy blood

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#32]
My latest seed has Tailtiu assigned both major Baldr and minor Dain bloods. Not quite sure how that happened. Holy blood randomization was 75% minor/25% major/0% none.

**Comment by lushen124** [comment]
Just curious, what was Sigurd's blood? I suspect the logic to try to avoid Sigurd's blood inadvertently gave her major blood. 

Actually, looking at the logic I have for it, it's possible if, say, she had minor Dain and Sigurd had major Dain. In the class randomization phase, this is ok, because she wouldn't get a holy weapon. But when it comes time to give out holy blood (assuming the option is enabled) then if she rolls Major, then I can't promote Dain because Sigurd has it. Instead, it tries to look for another major blood to give. Perhaps that other blood should be minor instead of major in that case.

**Comment by Hozu** [comment]
Sigurd did have major Dain blood, yeah.
