### ISSUE TITLE
Suggestion: Relative Growths

### ISSUE THREAD

**Issue by SdeSpencer** [lushen124/Universal-FE-Randomizer#33]
Preface: I have no idea how hard this would be and PLEASE tell me if i'm overexplaining something / accidentally being condescending or an idiot or something

Just an idea, but Relative Growths: Basically the idea of changing growths of a randomized recruitment character to be relatively the same as the original character, the same general way as Relative Bases (ala highest growth to highest growth, second highest to second highest, ect ect.) 

of course this would also have a few nuances, as it would need to be before any other randomization (the same way that relative growths needs to be). Aka the order of operations would be 

0. (implied class change / randomization)
1. Relative Growths
2. Growths Randomization
3. Reverse/Forward leveling (if applicable, otherwise other Randomized Recruiting bases setting)
4. Bases randomization.
5. Basically everything else character related.

**Comment by lushen124** [comment]
Makes sense to me, but I just want to make sure I fully understand what you mean. What I will say is that the current order of randomization is essentially random classes before everything else (assuming that option is enabled), then all the other changes (growths, bases, etc.) and then finally recruitment is the last thing that gets modified. Ideally all options relating to recruitment happen at the same time, which is how things happen right now (everything in the same box in the GUI gets processed in a chunk before moving on to other boxes). So by the time we get to the recruitment box, everything else will have already been randomized.

So here's what I'm thinking for this, and let me know if I'm misunderstanding anything.

Relative growths is an option that is available if matching bases or relative bases is selected for random recruitment. I think this option makes less sense with autolevel, but it could be an option regardless (it'd just suck for Karel -> Roy). What would happen is that, characters get shuffled into different slots, base adjustment happens with the character's usual growths, and then relative growths will change growth rates for characters based on the slots they occupy, matching the highest growth rate of the slot to the character's highest growth rate (perhaps disregarding HP, since that growth rate is usually out of line with the others), and matching everything else down the line in order.

The other option (or if the option is not selected) is to keep growths (which is what Yune does today).

**Comment by SdeSpencer** [comment]
Ok my suggestion was slightly different than that. most things are correct and work (it's just a slightly different order than initially made sense in my brain), but my suggestion for autolevel was that it effectively use their new relative growth instead of their old growth. If that just straight up doesn't work with the current functioning, that's fine, it's just how i imagined Autolevel + Relative Growths would work. I'd kinda recommend not having Autolevel + Relative Growths if that couldn't be an option.

**Comment by lushen124** [comment]
I think we're confusing two separate operations into one. The case you listed above requires certain options selected to make sense. Specifically:

* Randomized Recruitment (fair enough)
* Growths Randomization Enabled (this is disabled by default)
* Bases Randomization Enabled (this is disabled by default)
* Autolevel base stats (this is the default, but there are two other options)

Since the logic needs to work for any combination of those settings above, let me suggest breaking it down into a separate operation.

* Master Randomized Recruitment Enable Checkbox
  * Group for Growth Options (select 1)
    * Use Fill Growths - Uses the growths of the filling character. (this is what Yune does today)
    * Use Slot Growths - Uses the growths of the character being filled.
    * Slot Relative Growths - Adapts the growth spread of the filling character to growth rates of the character being filled (I think this was your original idea).
  * Group for Bases Options (select 1)
    * Autolevel Base Stats - Uses the character's growth rates to simulate level ups and downs to reach the target level.
      * Group for Autolevel Growths (select 1)
        * Use original growths - Uses the filling character's original growths. (this is what Yune does today)
        * Use new growths - Uses the character's target growths. (I think this is what you're proposing)
    * Match Base Stats - Uses the bases of the character being filled.
    * Relative Base Stats - Adapts the base spread of the filling character to the base spread of the character being filled.

Does that make sense?

**Comment by SdeSpencer** [comment]
Yeah that makes sense. Sorry i've kinda been set into a loop a few times but i think i get it and that makes more sense than anything i've thought of.
