### ISSUE TITLE
FE4: Can obtain duplicates of Altena's holy weapon

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#38]
Can't believe I missed this one. You can sell Quan's holy weapon in gen 1, and buy it with someone else. Since Altena has that same item added to her inventory in gen 2 (presumably because Quan can lose it when he's a green unit), you can end up with two copies of the same item.

Easiest solution would be to simply not give Quan his holy weapon in gen 1, since by time he gets it there are only pirates to kill, and the arena if it's not cleared. But that's a deviation from vanilla, so it might be better to treat the weapon like Sigurd's holy weapon - add it to the excluded inherited items list, and blacklist all other units from getting the same major holy blood as Quan.

There is one lingering question with the latter method, however. Can Sigurd and Quan be allowed to have the same holy blood? The potential issue comes from chapter 5, when Quan appears as a green unit. If someone else has his holy weapon from earlier, and you do a save and reset, what happens? I'm inclined to believe nothing will get removed, since enemies in gen 2 that are given drops don't lose them if you already have those items. The only reason I can think of that those two couldn't have the same holy blood is if the weapon held by a player unit gets lost, which I don't think would happen. I can verify it in a couple of days once I reach chapter 5.

**Comment by lushen124** [comment]
Sigurd and Quan are the only two that can share holy blood since Gae Bolg doesn't pass down the regular way in vanilla anyway, but given this specific issue, I think removing Gae Bolg from Quan in Gen 1 when you control him is too big of a change from vanilla. I could add Quan's weapon to the blacklist as well, but that's now either two holy weapons that can be lost in inheritance or two holy bloods that are off limits once they're assigned. Quan's is less of an issue since he only has access to Lances and Swords anyway, which always have an alternative. But combined with the fact that Sigurd can also have a Lance blood, this might end up affecting blood assignment for lance-locked classes (in the same way Sigurd can completely lock down fire mages if he gets Fjalar).

So we can go one of two ways. One is to revert the logic for Sigurd and just let those weapons be lost if that's the case and the other is to apply the same logic for Sigurd to Quan, further limiting the blood pool for the other characters.

**Comment by Hozu** [comment]
I think the potential chance of locking out both major lance bloods in gen 1 is better than having multiple copies of a holy weapon be lost simply because it's the same as what Sigurd (and Quan) has. It only locks out a couple of units who don't have major blood in vanilla from getting a holy weapon - the ones who get an item by event. And that's if they end up in a class that is limited to a blood that's blacklisted. Though more units do get to miss out on the major blood in general.

Although... theoretically, you could blacklist the bloods just on the units who are guaranteed to get a holy weapon in gen 1 - Lewyn, Claud, and Brigid. Their holy weapons won't appear in gen 2 if not inherited, but if other items become holy weapons, they can be obtained eventually... even if the worst case scenario is having to spend 50k gold to buy it back all the way in chapter 10 (ie. if a holy weapon replaced Edain's Rescue staff). If you go about things that way, you would have to add a warning that all copies of Sigurd's and Quan's holy weapons can't be inherited.

**Comment by lushen124** [comment]
Well, each operation is done separately, so in the first pass, it's done when classes are assigned, so it only affects the natural major blood members (Sigurd, Quan, Brigid, Claud, and Lewyn). There's logic to make sure Quan, Brigid, Claud, and Lewyn can't get assigned a class that only has one major blood choice which belongs to Sigurd (e.g. if Sigurd has Fjalar, none of those 4 can be Fire Mages, admittedly only an issue for Lewyn).

The second step is the blood assignment step where some characters can be assigned arbitrary major or minor blood, which would then affect everybody without major blood naturally. Since classes are already set, I'm not going to go back and change them (since depending on the character and/or the change, that can cause a chain reaction of other changes). Using the prior example, if Ayra were a minor Fjalar fire mage (which is valid from the class randomization step, since minor blood is not restricted from matching Sigurd's blood type), she may have to break the optional rule about matching blood to weapon usage, and the potential restriction of being assigned minor blood even if the user wanted 100% major blood. Now, maybe this is an very unlikely edge case, but it'd still need to be handled. 

The other alternative is to take one of the unused weapon slots and make it into a copy of the holy weapon for Altena (you'd just lose the kill count on it, which probably isn't that high considering Quan's limited time with it), since while the problem is similar to Sigurd's, it's not actually the same problem. The only drawback is that you lose a enemy holy weapon, but since that's never guaranteed in any option, it's not a real rule that there needs to be 7 enemy holy weapon drops.

**Comment by Hozu** [comment]
Just a heads up, if one does sell Quan's holy weapon before he leaves, it will disappear when you do a save and reload while ch 5 Quan is around. ie. if blacklisting both Sigurd's and Quan's bloods, those two can't share the same one. So yeah, that would leave 10 of the 12 available bloods for other units in gen 1.

Hmm... you know what, the idea of giving Altena an entirely different item for her holy weapon does sound like it could be a good idea, but there might be some problems. You would want to have an enemy in ch 10 onwards drop the gen 1 weapon (if using the bosses have holy weapons option), since I'm fairly certain if she inherits the old one, the new one will replace the old one (the exception to this seems to be items that would appear in the ch 6 shop if not inherited, the new starting items just disappear entirely... maybe it decides the shop items before setting the characters?). I know in vanilla if you have Arthur inherit a wind tome, the one he has is the one from gen 1 due to kills, while the other one appears in the shop, so I believe guaranteeing one boss to drop the holy weapon Quan gets in ch 10 or endgame will still have it drop if it's inherited, it would just be the other one. Shame there isn't a way to guarantee the removal of Quan's holy weapon, since he may die first, or players may seize the castle first.

I suppose the blacklisting of bloods would be less of an issue if bloods were assigned first, but I imagine changing that would take an unreasonable amount of effort...

**Comment by Hozu** [comment]
By the way, the idea of having two instances of Quan's holy weapon will only work if you're able to have the ch 3 and ch 5 instances be different, due to the duplicate item thing causing one to be lost on save and reset. ie. Quan should receive a holy weapon of a different item ID, rather than Altena.

**Comment by Hozu** [comment]
I've done some more thinking regarding blacklisting Quan's holy blood on others. Since you have class generated for everyone first, then assign bloods afterwards, would it be possible to say... have Quan locked out of Duke Knight if Sigurd randomizes into a class that can wield lances if randomize lords is on (ie. the only promoted lance-locked class), then when assigning blood, if Sigurd has a lance blood, to lock Quan out of *both* lance bloods? That way, one major lance blood is available to everyone else, so you don't have additional class lines locked out of holy blood by blacklisting both Sigurd's and Quan's bloods.

Although, that doesn't address the issue of Sigurd's blacklisted blood locking out certain classes from getting a major blood if he gets certain holy bloods (ie. fire mages, archers, hunters, snipers, bow knights, arch knights, axe knights, great knights, armoured axes, brigands, and barbarians). That's a different issue (I don't know if it's resolved?), though it might be able to be resolved by determining both Sigurd's class and blood before even assigning classes for other units, and blacklisting appropriate classes as needed.

**Comment by lushen124** [comment]
The logic right now doesn't lock anymore classes than necessary, so when Quan comes along, all he's limited to is not sharing a class that only has Sigurd's blood as its only option. Since Quan himself is limited to Sword and Lance blood, this isn't usually an issue, but he could, together with Sigurd, kill the Lance option for major blood. Sigurd is also kind of special in that the logic kind of relies on him getting his class assigned first, which is a nice coincidence since he's character 0. Quan, by contrast, is character 6, so there's 5 characters that might be screwed between the two. Luckily, none of those 5 characters have major blood normally, so it's less of an issue until you start wanting to assign holy blood to characters that didn't have blood before.

But I thought of an easier solution: just don't give out more than one copy of Sigurd's holy weapon. This has nothing to do with the character's holy blood, so long as only one copy of Tyrfing (or whatever his weapon is) exists. No matter who has it, nobody's going to be able to pass it down. It won't be available until Palmark gives it back to you in Ch. 10. So this restricts no classes (except for the aforementioned gang of natural holy blood carriers Quan, Lewyn, Claud, and Brigid), but it just means they can't get a second copy of a weapon that won't pass down properly.

**Comment by Hozu** [comment]
I suppose you could do that, but if say Lewyn got the same blood as Sigurd, would that make it so he doesn't get a holy weapon from his event in chapter 4? Or will the characters who always get a holy weapon not have the ability to have the same blood as Sigurd or Quan?

Although, do you mean that those weapons won't have the potential to have multiple copies in gen 2 either?

In any event, there probably should be a notification somewhere that tells people that the holy weapon that both Sigurd's and Quan's have can't be inherited by gen 2 units, and will appear in their original locations (Palmark in ch 10 for Seliph, and on Altena for Altena).

**Comment by lushen124** [comment]
Everything I'm talking about is limited to Gen 1. So let me just run it all down.

When determining classes, if the character is a Gen 1 character, is not Sigurd, and naturally has Major Blood, then their new class (assuming the option to randomize holy blood is enabled) is guaranteed to **not** be a class that requires them to have Sigurd's blood, so they will never share a blood with Sigurd. This means Quan, Lewyn, Brigid, and Claud will all have their holy weapons, and none of them will be the same as Sigurd's (or Quan's) since they can't have the same blood as him.

When assigning holy blood, if the character is a Gen 1 character and gains major blood, they have a chance of receiving a holy weapon **if and only if** their major blood does not match Sigurd's (or Quan's). This means any character not in the first case can receive any major blood, but only if their major blood doesn't match Sigurd's (or Quan's) do they have a chance of getting a holy weapon. Since those that naturally have major blood aren't eligible to receive additional blood, they are unaffected in this step.

**Comment by Hozu** [comment]
Okay, that works. As long as there's a tooltip somewhere that will notify players that Sigurd's and Quan's holy weapon explicitly can't be inherited by anyone and will always appear at their vanilla notification instead.

Although... do you want to still address the duplication glitch in chapter 5 where if you save and reset anyone holding Quan's holy weapon loses it if he's around as an NPC? You would have to use one of the 7 items that are currently allowed to be holy weapons with the force holy weapons on boss setting/staves? without that setting, and give that to ch 3 Quan instead (ie. ch 3 Quan gets item 0x12 for his holy weapon instead of 0x...3E?). Then that weapon would end up being a boss drop somewhere in gen 2 with the force holy weapons on boss setting (ie. one of the eligible bosses is forced to have an eligible class for the weapon + the blood) and then... I'm not sure how you want to handle it when that option isn't being used.

**Comment by lushen124** [comment]
I think that's less of an issue because it requires two things. 

1. You have to sell that weapon and somebody else has to have bought it.
2. You have to reset in the 3 ~ 5 turns Quan is alive in Ch. 5.

Considering Quan is supposed to die anyway and that he'll lose his weapon anyways when Ethlyn dies, it's a very temporary issue that's probably more trouble than it's worth to fix, since the problem fixes itself anyways in a couple of turns. If you lost your weapon instead of Quan losing his, that would be a bigger issue, but since Quan is the one that loses it, then I think it's a low priority issue at best.

**Comment by Hozu** [comment]
The copy you sold earlier is the one that gets lost on save and reset, not the one NPC Quan has. It seems that the last copy of the item that was created is the one that remains... that's consistent with Julia keeping the Circlet in endgame if you sold it from Deirdre and inherited it in gen 2.

**Comment by lushen124** [comment]
Oh, so it is the one that you have. That's a bit more of an issue, but still, considering it can't be passed down beyond Ch. 5, that's still not *that* big of an issue. Again, the fix would be pretty difficult unless I knew how to change NPC Quan's inventory.

**Comment by Hozu** [comment]
I think it should be okay as long as people know about it.

**Comment by Hozu** [comment]
Funny thing I came across, I removed Altena's holy weapon from her starting inventory, and sold the holy weapon from Quan in chapter 3, but I ensured that NPC Quan kept his holy weapon by seizing the castle before Ethlyn got killed, and... Altena inherited the holy weapon. Worth nothing if you intend on exploring other possible solutions later, as this can throw a wrench into things.

**Comment by lushen124** [comment]
So it's inheritance from Ch. 5? That's just weird, because she gets all of Quan's weapons from Ch. 3 as well. If Quan were sell his Ch. 3 version (or not pick it up) and then goes on to lose his weapons in Ch. 5, then she'd end up with no holy weapon at that point.

**Comment by lushen124** [comment]
Ok, let's give 0.8.1 a shot. If there are more issues, we can create more tickets.
