### ISSUE TITLE
[FE7] Randomize Lords crashes when trying to assign palettes

### ISSUE THREAD

**Issue by isloat** [lushen124/Universal-FE-Randomizer#395]
![image](https://user-images.githubusercontent.com/5470840/172873932-a3f545f2-4b72-433a-bb4d-3a6b8db18fb9.png)

All other settings not visible in the screenshot are turned off. Turning off Include Lords allows the randomizer to compile without problem. This setting works properly for FE6, so it seems to be a problem specific to FE7.

**Comment by Geeene** [comment]
Hi,

the issue here is that the randomizer takes the characters from the Map that contains the Randomized Character mapping. This map will not contain Lyn / Eliwood / Hector, if they aren't being randomized.
So when the randomizer tries to get them from the map it blows up since it can't find them, and currently only checks that the Map exists, not that the character also is in the map.

Since at this point it is an expected scenario, we should check that if the lords are not in the map, then we just use the default Lyn / Eliwood / Hector character slot, since they aren't randomized.

This way it works:
![2022-11-27 16_52_23-Yune - Universal FE Randomizer_src_random_gba_randomizer_GBARandomizer java - Ec](https://user-images.githubusercontent.com/41942612/204144468-6e2e0761-100a-4825-a6e8-b42e0dc1750c.png)

**Comment by lushen124** [comment]
Addressed with #400.

**Comment by isloat** [comment]
Excellent, thank you! Looking forward to the new release.
