### ISSUE TITLE
Suggestion: Proportional class randomizing

### ISSUE THREAD

**Issue by Enaluxeme** [lushen124/Universal-FE-Randomizer#43]
Makes sure that there aren't too many units with the same class and that there's at least one unit of every class when possible.

**Comment by lushen124** [comment]
The first part of that is a bit vague (how many is too many?) and the second part of that may not necessarily be possible (if number of classes > number of characters).  I suspect what you're getting at is that you want an option to avoid duplicate classes as much as possible. 

How about an option for class shuffling, instead of class randomization? I think most games probably have a decent enough mix to be considered "proportional" by your definition.

**Comment by Enaluxeme** [comment]
I'm pretty sure there's no game where the number of classes (or rather,
class trees) is higher than the number of characters.
I guess class shuffling is still an option someone may like, but IMO that
would get monotonous, in a way. Also, classes like the dancer are made to
be unique.

I understand that 'too many' is a bit vague, but that's why I said
proportional. The logic behind the script should be not to give 3 units the
same class unless there's already 2 units for every other class (excluding
special classes that should be given only once).

Il mar 12 mar 2019, 4:01 AM Shen Lu <notifications@github.com> ha scritto:

**Comment by lushen124** [comment]
Fair enough. I'll add this for the 0.8.3 release.

**Comment by Enaluxeme** [comment]
Thank you! It's very nice of you to listen to everyone like this, I
appreciate it.
Do you accept donations?

Il dom 24 mar 2019, 7:29 PM Shen Lu <notifications@github.com> ha scritto:

**Comment by lushen124** [comment]
Nah, I'd rather keep it clear that I do this as a hobby and not as a job. 🙂 

Thanks for offering though.
