### ISSUE TITLE
FE4: Fee can be in a different class from Erinys despite strict child matching

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#58]
I've come across some seeds where Fee is a Pegasus Knight despite Erinys being a Dracoknight. However, I think the issue has something to do with Erinys, since in the almost 60 seeds I've generated from initial FE4 support release, I have not once seen her randomize into a Pegasus Knight. It took a while for Fee to be able to randomize into a Pegasus Knight as well - probably around 0.7.6f or 8.0.

I know you don't allow units to randomize into the same class as their vanilla class, unless they have some other kind of restriction (ie. must be mounted or must be a flier), so I'm confused as to what could be causing Erinys to never become a Pegasus Knight. Particularly when Fee is one. Perhaps somewhere it believes that Erinys is also one, but she's changed later?

**Comment by lushen124** [comment]
I believe this is the same issue/feature to allow characters to randomize into the same class. This is especially limiting because Pegasus Knights and Wyvern Knights are basically locked to the opposite. I'll get this into the next release as well.

**Comment by lushen124** [comment]
I'm actually a little confused as to how Fee can become a pegasus knight, because the code directly sets the class to match the analogue (in this case, Erinys). Once characters have their class assigned, they shouldn't be changing again, and all of Gen 1 is assigned before Gen 2 is considered (and even in Gen 2, children are processed last).
