### ISSUE TITLE
FE4: Light Priestess valid promotion issue

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#62]
With any promotion option outside of fully random promotions, Light Priestess requires at least minor Naga to maintain light magic weapon rank on promotion. The class has A in light magic, but the only valid promotion option, Sage, has B rank in light (not that any other promoted class has A rank in light). The problem is, it's not a guarantee to have a Light Priestess with any Naga blood. Case in point, the last seed I generated has Light Priestess Lachesis with major Bragi blood, who gets Aura by the talk event with Dew. But when she promotes, she loses access to Aura!

There are a couple of potential solutions, but each has their own things to deal with:

1) Decrease the light magic rank of Light Priestess to from A to B. While this seems like a similar solution to removing the Charm class skill from Princess, there is one generic Light Priestess - the deadlord Canis, when bosses are not randomized. That can be "fixed" by giving her minor Naga blood, since she is a holy character. However, when randomizing enemies, this prevents any generic Light Priestess from having Nosferatu or Aura. I believe you've disabled enemies from getting that class, but it turns out the bug report about the issue with that may have been faulty. [Generic enemy Light Priestess does work, as long as the enemy is explicitly a female one](https://i.imgur.com/5FHT2U3.gifv).

2) Increase the light magic rank of Sage to B to A. This lets more units than normal use Aura and Nosferatu, which in turn probably allows for more of those tomes to be assigned. More of a break from vanilla than the first solution.

3) Decrease the rank of Aura and Nosferatu from A to B. Similar to the above solution, but it also allows Bard with minor Naga blood to use those two tomes. Light magic rank is still lost on promotion, but the weapon rank loss is functionally meaningless.

4) Ensure that anyone who is a Light Priestess has at least minor Naga blood. This requires some randomization logic changes. Stuff like characters with no holy blood being excluded from the class entirely, or the minor/major blood being forced to be Naga (double minor blood will always yield minor Naga/Bragi).

As an aside, generic enemies can be allowed to be a Light Priestess as they work, but only for enemies that are explicitly female. Which is what vanilla does with the lone enemy Light Priestess anyway...

**Comment by lushen124** [comment]
Correct with the light priestess on enemies bit. I could go and change enemy units genders as I want, since I don't think those matter that much.

As for the 4 solutions, I'm actually more inclined to opt for option 2 of giving Sage access to A rank light magic. Yeah, it means more characters can use the tomes, but I think that's more liberating and I also think Sage with B rank in light magic is a mistake in the original game, as no B rank light tomes exist (unless the wiki is lying to me again). This is the easiest solution.

1 isn't hard, but it's depriving Light Priestess from two tomes she should be able to use.
3 isn't hard either, but it's still a bit weird for a Light Priestess going from A rank to B rank, even if it doesn't practically mean anything.
4, as you said, is much more complex, as it would also need to bar characters from becoming light priestess if they can't have holy blood (based on whatever options are selected).

**Comment by Hozu** [comment]
Yeah there are no B rank light tomes. Makes me wonder if they planned on having a minor Naga Sage at some point. Or more likely, a B rank light tome (perhaps Nosferatu, since Aura would have been able to be passed onto gen 2 if it were B rank).

A rank light magic on Sage though, that will make things more interesting.
