### ISSUE TITLE
Suggestion: Include Creature Campaign characters in Recruitment Randomizer?

### ISSUE THREAD

**Issue by LancetheGallade1500** [lushen124/Universal-FE-Randomizer#67]
In a similar vein to the suggestion about allowing both male and female characters to be in the same recruitment pool, I'd like to see the characters from FE8's Creature Campaign (those being Caellach, Orson, Riev, Ismaire, Selena, Glen, Valter, Hayden, Fado, and Lyon) added to FE8's main recruitment pool. While it would be nice to eventually have the people in the story match whoever their Creature Campaign equivalents become, I'd personally much rather have them added to the recruitment pool first.

Also note that I haven't entered Creature Campaign in a randomized file nor have I examined the code, so I don't know if there's anything more complicated that would prevent this from occurring. I also don't know if the playable Orson from Chapter 5x uses the same data as the one from Creature Campaign.

**Comment by lushen124** [comment]
It's a bit weird for a few of those characters, but it could work. Though now I'm thinking that maybe randomizing bosses with playable characters for recruitment might be interesting.

But as for what we could do as a first step, those that are naturally not playable and are not enemies until the end could be randomized. That would include Ismaire, Glen, Hayden, and Fado. The other ones would be full on enemy/PC replacement, since if I replaced Valter from end game, it'd only make sense to replace him everywhere else, so I'll leave the other characters for a future option.

**Comment by LancetheGallade1500** [comment]
That could work! I was actually specifically thinking of those two first, because I just got to the point in my randomized playthrough where Ismaire died, and I've always liked Glen and Cormag.
