### ISSUE TITLE
GBA FE suggestion: Class scaled Constitution? 

### ISSUE THREAD

**Issue by TTTTTsd** [lushen124/Universal-FE-Randomizer#88]
While I was doing some runs with the randomizer, I noticed Constitution is really troublesome to play around with, even with the minimum CON setting. I would often get very useless axe units even with Minimum CON set to 15 to test.

Perhaps an option to scale a character's constitution based on the highest and lowest CON stats of the class they're in? i.e. an Axe Fighter can have anywhere from 11 to 13 CON, etc.

It's a fairly minor issue but it's come up a lot in my usage of this program.

**Comment by lushen124** [comment]
Maybe it's worth only modifying the character's personal CON instead of taking their class CON into account. Right now, it uses a character's normal final CON (which means it's likely that an axe fighter Sophia will retain her 3 CON). Every class has a base CON that kind of represents what their CON should be around, and the usual personal CON is probably +/- no more than 2. Assuming a +/- 2, all axe fighters would fall between 9 and 13 CON.

**Comment by TTTTTsd** [comment]
I think that would be ideal. Simply having an option for Personal CON without taking class CON into account so that they can still function in the classes they're randomized into. Maybe have it as an option so that the current CON settings can be used as well for those who want that level of challenge.

**Comment by lushen124** [comment]
I've decided to make this into the default behavior, since it makes more sense to me that a character randomizing into a class be able to adeptly use the weapons the class can normally use as opposed to them still having the build of their original class. 🙂
