### ISSUE TITLE
Suggestion: Class Exceptions and Randomized Recruitment

### ISSUE THREAD

**Issue by SdeSpencer** [lushen124/Universal-FE-Randomizer#92]
Preface: I have no idea how hard this would be and PLEASE tell me if i'm overexplaining something / accidentally being condescending or an idiot or something

This is mostly based on the lack of an ability to avoid changing classes so i had an idea (two actually, but they're related)

1. The Exceptions in randomizing classes should prevent randomization by *slot* as opposed to proper character (aka, the person who takes Erika's place in the story would be the Erika lord class 100% of the time with "Randomize Lords" unchecked, but Erika could be anything if she wasn't in that slot)

2. Add an option to not randomize certain groups of characters in Randomized recruitment (ala Lords, Thieves, whoever else). They'd still be able to be randomized class-wise if you have that option, just the character would be in the same place as before. 

Would these work?

**Comment by lushen124** [comment]
1. I'm not sure if that's obvious. Maybe it could be an option though. It seems like you'd only be changing the face, effectively. It also runs counter to how Reverse Recruitment patches normally work, which use the fill character's class instead of the slot character's class.
2. This is probably ok. It's just a matter of removing characters from the pool if the user selects the option.

**Comment by lushen124** [comment]
What I was thinking by adding this option in the recruitment box is that, say, if you want to exclude randomizing the recruitment of Lords, then Eirika and Ephraim do not change their positions in the game. If you wanted to exclude thieves from randomized recruitment, that would mean Colm and Rennac join when they normally do. Everybody else joins randomly. 

This logic is consistent regardless of any other setting in any other group. It's not immediately clear to me that a character's class may change arbitrarily even if I don't have any of the randomize classes options checked (arbitrarily meaning not a promotion/demotion) and randomized recruitment does not require randomized classes to be enabled. As an example, it seems odd to me that Garcia would randomly become an Eirika lord even if I disabled class randomization simply because he was randomized into Eirika's spot, considering nobody else would have changed their class.

**Comment by SdeSpencer** [comment]
Ok wait i'm confused. What you are saying is correct, it's just you seem to have misunderstood what my idea was in a way i did not expect.

aka, Option 1 would be under "randomize classes" (the original idea was in the same place as the current include lords/thieves) and would only BECOME an option when classes are randomized. AKA, if classes were randomized, you could set it so that whoever was in Erika's spot (whether it was Erika or not, in your example Garcia) would become an Erika Lord. 

Option 2 would be under "randomized recruitment" and would be an option when randomized recruitment was on. AKA Erika and Ephraim (and/or Colm and Rennac and/or other options) would just not change positions.

**Comment by lushen124** [comment]
If an option is under the Classes section, then it should only affect class randomization. I'd like to keep options inside their respective boxes instead of bleeding out into other boxes (because then it becomes very difficult to understand why certain boxes may or may not be enabled).

If I understand you correctly, both of your suggestions are about randomizing recruitment, but your first point seems to be referencing an option in the classes section. I can duplicate the options from classes section into the recruitment section, but they would mean something different, which is what your second point (I think) was referring to. 

I feel like the more direct option would be to do like what we did with the growths and bases and just give the option of either using the fill class or the slot class, where the fill class is the default option (and the one we use today) and the slot class is what you're suggesting. And maybe this is what you were getting at from the start. The important part is that this option would be under the Recruitment section and not the Classes section, and it would apply to more than just Eirika's (or Ephraim's) slot.

**Comment by SdeSpencer** [comment]
Ok now I am confused. 
Are you suggesting Fill Class / Slot Class would affect my second idea (Ala stopping randomized recruitment), but if you checked "slot class", it would also stop any randomization of classes in that slot that might've happened in the meantime? 
Or are you suggesting that class randomization exceptions in general would move to the Recruitment section, and that "fill class" would stop them from randomizing the class of the character and "slot class" would stop them from randomizing the class of the character's slot
Or are you suggesting adding a new option in the recruitment section (that probably only is open if you choose to randomize classes) that asks what Class randomization exemptions should affect, with "fill class" meaning it affects what the character is randomized to and "slot class" meaning it affects whatever character is currently in the original slot?
The last one makes sense, but the first 2 seem weird, and i can't tell which you're referring to.

**Comment by lushen124** [comment]
Alright, let's back up a little bit. Let's go back to what your initial suggestion was

> The Exceptions in randomizing classes should prevent randomization by slot as opposed to proper character (aka, the person who takes Erika's place in the story would be the Erika lord class 100% of the time with "Randomize Lords" unchecked, but Erika could be anything if she wasn't in that slot)

This one confuses me because you're referring to an option in randomizing classes be based on slots when class randomization does nothing with slots. The terminology of slots and fills are referring to recruitment randomization, not class randomization. Class randomization only deals what classes the characters should be. Recruitment randomization only deals with when characters join. These two options are independent of each other.

What I suggested earlier was to add an option under Recruitment for characters to either:

* Use Fill Class - Characters use their own class (promoted or demoted).
* Use Slot Class - Characters use the class of the character they replace (promoted or demoted).

Yune currently uses the first one. I think what you're suggesting is the second one (assuming classes haven't been randomized). Let's use an example too. Let's say we have the following substitutions and you didn't randomize classes.

Neimi -> Eirika
Gerik -> Seth
Saleh -> Franz

With **Use Fill Class** (what Yune does today):

* Neimi becomes an Archer
* Gerik becomes a Hero/Ranger (random due to branching promotions)
* Saleh becomes a Mage/Priest/Pupil (random due to branching demotions)

With **Use Slot Class** (what I think you're looking for):

* Neimi becomes a Lord (Eirika)
* Gerik becomes a Paladin
* Duessel becomes a Cavalier

> Add an option to not randomize certain groups of characters in Randomized recruitment (ala Lords, Thieves, whoever else). They'd still be able to be randomized class-wise if you have that option, just the character would be in the same place as before.

This is totally fine. This just makes sure Eirika/Ephraim and/or Colm/Rennac don't move from their normal join times.

**Comment by SdeSpencer** [comment]
Ok that makes sense, it just feels like a roundabout solution to my original suggestion. Thanks for explaining.

**Comment by lushen124** [comment]
The reason I phrase it that way is because it has to work with any combination of settings. I can't have a setting inside of class randomization that only makes sense when recruitment randomization is enabled (nor vice versa). Classes can change during recruitment randomization, but they should follow some rule not dictated by RNG (otherwise, that's just stealth class randomization). That's why I'm formalizing what exactly is changing in the option and how it's being changed.
