### ISSUE TITLE
Suggestion: Force Change when randomizing Class/Recruitment

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#97]
I think it would be neat to have a toggleable option (or rather, two distinct options, one for classes and one for recruitment) when randomizing Recruitment and Classes of playable characters (it could be done for enemies and bosses as well, but playable characters are the ones players would be most interested in I think) to **force** characters to change their classes and recruitment time, basically to prevent them from keeping the same class and/or join time as in vanilla FE8. I have no idea how hard it would be to implement.

**Comment by lushen124** [comment]
For class randomization, this is probably ok, though there is also similar logic for some characters (but generally speaking, there's always an alternative class that fits the bill), but for recruitment, there's actually logic to make sure I don't accidentally assign an invalid character to an invalid slot. For example, I have logic that makes sure all fliers are assigned characters that are fliers, since scripted flier movement can break the game. On the off chance that only one flier exists, then it can't guarantee nobody gets the same slot as they started as. Other examples of restrictions are characters that have scripted attacks (for example, FE7 Erk in the Lyn chapters is scripted to attack at range). There's even more restrictions if crossing genders isn't allowed.

**Comment by koumal8** [comment]
Forcing class change would already be enough for me; if you e.g. need 2 fliers in Fe8 (Cormag and Tana, I think?) you could even put in place a logic where the program first chooses 2 random characters and assigns them random flying classes, and only then randomizes the rest of the cast.

**Comment by lushen124** [comment]
Normally fliers aren't the issue because all fliers, by default, only randomize into other flier classes, so there's never a case where I should have too few fliers (though with the gender restriction, there is a chance that there's only one choice (FE8 Cormag comes to mind)). The thing with a force change in recruitment is that the pool has to have at least 2 choices in order to make sure it changes, and that's not always possible, depending on the constraints.

I'll go ahead and implement force class change, but let's revisit force recruitment change later.

**Comment by lushen124** [comment]
So, the funny thing is, I forgot I made forcing a class change for playable characters the default setting. So it's likely you've already had this on from the very beginning. 🙃 

In any case, I went ahead and made it an option for GBAFE.
